#!/bin/bash

# In case we are being run from another service, set some stock paths

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/opt/usr/bin:/opt/usr/sbin:/usr/local/bin:/usr/local/sbin"

if [ "${1:-}" = "-y" ]; then
    RESPONSE=y
else
    echo "Files will be deleted.  Are you sure? (N/y)"
    read RESPONSE
fi
[ "${RESPONSE:-}" != "y" ] && [ "${RESPONSE:-}" != "Y" ] && exit

OPWD=$PWD
cd "`dirname "$0"`"
SAROOT=$PWD
[ -r bin32/sadoc ] && bin32/sadoc -stop >/dev/null 2>&1
[ -r bin64/sadoc ] && bin64/sadoc -stop >/dev/null 2>&1
rm -f bin32/.scRepository*
rm -f bin32/createcert
rm -f bin32/createkey
rm -f bin32/dbbackup
rm -f bin32/dbconsole
rm -f bin32/dbdsn
rm -f bin32/dbeng12
rm -f bin32/dbeng12.lic
rm -f bin32/dberase
rm -f bin32/dbexternc12
rm -f bin32/dbfhide
rm -f bin32/dbinfo
rm -f bin32/dbinit
rm -f bin32/dbisql
rm -f bin32/dbisql_32.rep
rm -f bin32/dbisqlc
rm -f bin32/dblic
rm -f bin32/dblocate
rm -f bin32/dblog
rm -f bin32/dbmlsync
rm -f bin32/dbns12
rm -f bin32/dbping
rm -f bin32/dbremote
rm -f bin32/dbspawn
rm -f bin32/dbsrv12
rm -f bin32/dbsrv12.lic
rm -f bin32/dbstats
rm -f bin32/dbstop
rm -f bin32/dbsupport
rm -f bin32/dbsvc
rm -f bin32/dbsvc_scripts/dbsvc_iface
rm -f bin32/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin32/dbsvc_scripts/dbsvc_iface_rh
rm -f bin32/dbsvc_scripts/dbsvc_iface_suse
rm -f bin32/dbsvc_scripts/distro.sh
rm -f bin32/dbsvc_scripts/svc_functions
rm -f bin32/dbsvc_scripts/svc_t_common
rm -f bin32/dbsvc_scripts/svc_t_dbmlsync
rm -f bin32/dbsvc_scripts/svc_t_dbns
rm -f bin32/dbsvc_scripts/svc_t_dbremote
rm -f bin32/dbsvc_scripts/svc_t_mobilink
rm -f bin32/dbsvc_scripts/svc_t_network
rm -f bin32/dbsvc_scripts/svc_t_personal
rm -f bin32/dbsvc_scripts/svc_t_rshost
rm -f bin32/dbsvc_scripts/svc_t_rsoe
rm -f bin32/dbsvc_scripts/svc_t_standalone
rm -f bin32/dbsvc_scripts/utility.sh
rm -f bin32/dbtran
rm -f bin32/dbtsinfo
rm -f bin32/dbunload
rm -f bin32/dbunlspt
rm -f bin32/dbupgrad
rm -f bin32/dbvalid
rm -f bin32/dbversion
rm -f bin32/dbxtract
rm -f bin32/htmlview
rm -f bin32/language/de/messages.txt
rm -f bin32/language/de/usage.txt
rm -f bin32/language/en/messages.txt
rm -f bin32/language/en/usage.txt
rm -f bin32/language/fr/messages.txt
rm -f bin32/language/fr/usage.txt
rm -f bin32/language/ja/messages.txt
rm -f bin32/language/ja/usage.txt
rm -f bin32/language/zh/messages.txt
rm -f bin32/language/zh/usage.txt
rm -f bin32/mlarb12
rm -f bin32/mlarb12.lic
rm -f bin32/mlarbiter.sh
rm -f bin32/mlfiletransfer
rm -f bin32/mlgenreplayapi
rm -f bin32/mlmon
rm -f bin32/mlreplay
rm -f bin32/mlsrv12
rm -f bin32/mlsrv12.lic
rm -f bin32/mlstop
rm -f bin32/mluser
rm -f bin32/newdemo.sh
rm -f bin32/perlenv.pl
rm -f bin32/phpenv.php
rm -f bin32/rsaroot.crt
rm -f bin32/rsaserver.id
rm -f bin32/rshost
rm -f bin32/rsoe
rm -f bin32/run_migrator.sh
rm -f bin32/sa_config.csh
rm -f bin32/sa_config.sh
rm -f bin32/sadoc
rm -f bin32/samonitor
rm -f bin32/samonitor.sh
rm -f bin32/samonitor.template
rm -f bin32/scjview
rm -f bin32/scvwde610.jar
rm -f bin32/scvwen610.jar
rm -f bin32/scvwfr610.jar
rm -f bin32/scvwja610.jar
rm -f bin32/scvwzh610.jar
rm -f bin32/smstart.dat
rm -f bin32/smstop.dat
rm -f bin32/sqlpp
rm -f bin32/uleng12
rm -f bin32/ulerase
rm -f bin32/ulinfo
rm -f bin32/ulinit
rm -f bin32/ulload
rm -f bin32/ulstop
rm -f bin32/ulsync
rm -f bin32/ulunload
rm -f bin32/ulvalid
rm -f bin32/usm.xsd
rm -f bin32/viewcert
rm -f bin32s/createcert
rm -f bin32s/createkey
rm -f bin32s/dbbackup
rm -f bin32s/dbconsole
rm -f bin32s/dbdsn
rm -f bin32s/dbeng12
rm -f bin32s/dberase
rm -f bin32s/dbexternc12
rm -f bin32s/dbfhide
rm -f bin32s/dbinfo
rm -f bin32s/dbinit
rm -f bin32s/dbisql
rm -f bin32s/dbisqlc
rm -f bin32s/dblic
rm -f bin32s/dblocate
rm -f bin32s/dblog
rm -f bin32s/dbmlsync
rm -f bin32s/dbns12
rm -f bin32s/dbping
rm -f bin32s/dbremote
rm -f bin32s/dbspawn
rm -f bin32s/dbsrv12
rm -f bin32s/dbstats
rm -f bin32s/dbstop
rm -f bin32s/dbsupport
rm -f bin32s/dbsvc
rm -f bin32s/dbsvc_scripts/dbsvc_iface
rm -f bin32s/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin32s/dbsvc_scripts/dbsvc_iface_rh
rm -f bin32s/dbsvc_scripts/dbsvc_iface_suse
rm -f bin32s/dbsvc_scripts/distro.sh
rm -f bin32s/dbsvc_scripts/svc_functions
rm -f bin32s/dbsvc_scripts/svc_t_common
rm -f bin32s/dbsvc_scripts/svc_t_dbmlsync
rm -f bin32s/dbsvc_scripts/svc_t_dbns
rm -f bin32s/dbsvc_scripts/svc_t_dbremote
rm -f bin32s/dbsvc_scripts/svc_t_mobilink
rm -f bin32s/dbsvc_scripts/svc_t_network
rm -f bin32s/dbsvc_scripts/svc_t_personal
rm -f bin32s/dbsvc_scripts/svc_t_rshost
rm -f bin32s/dbsvc_scripts/svc_t_rsoe
rm -f bin32s/dbsvc_scripts/svc_t_standalone
rm -f bin32s/dbsvc_scripts/utility.sh
rm -f bin32s/dbtran
rm -f bin32s/dbtsinfo
rm -f bin32s/dbunload
rm -f bin32s/dbunlspt
rm -f bin32s/dbupgrad
rm -f bin32s/dbvalid
rm -f bin32s/dbversion
rm -f bin32s/dbxtract
rm -f bin32s/htmlview
rm -f bin32s/language/de/messages.txt
rm -f bin32s/language/de/usage.txt
rm -f bin32s/language/en/messages.txt
rm -f bin32s/language/en/usage.txt
rm -f bin32s/language/fr/messages.txt
rm -f bin32s/language/fr/usage.txt
rm -f bin32s/language/ja/messages.txt
rm -f bin32s/language/ja/usage.txt
rm -f bin32s/language/zh/messages.txt
rm -f bin32s/language/zh/usage.txt
rm -f bin32s/mlarb12
rm -f bin32s/mlarb12.lic
rm -f bin32s/mlarbiter.sh
rm -f bin32s/mlfiletransfer
rm -f bin32s/mlgenreplayapi
rm -f bin32s/mlmon
rm -f bin32s/mlreplay
rm -f bin32s/mlsrv12
rm -f bin32s/mlstop
rm -f bin32s/mluser
rm -f bin32s/newdemo.sh
rm -f bin32s/perlenv.pl
rm -f bin32s/phpenv.php
rm -f bin32s/rsaroot.crt
rm -f bin32s/rsaserver.id
rm -f bin32s/rshost
rm -f bin32s/rsoe
rm -f bin32s/run_migrator.sh
rm -f bin32s/sadoc
rm -f bin32s/samonitor
rm -f bin32s/samonitor.sh
rm -f bin32s/samonitor.template
rm -f bin32s/scjview
rm -f bin32s/scvwde610.jar
rm -f bin32s/scvwen610.jar
rm -f bin32s/scvwfr610.jar
rm -f bin32s/scvwja610.jar
rm -f bin32s/scvwzh610.jar
rm -f bin32s/smstop.dat
rm -f bin32s/sqlpp
rm -f bin32s/uleng12
rm -f bin32s/ulerase
rm -f bin32s/ulinfo
rm -f bin32s/ulinit
rm -f bin32s/ulload
rm -f bin32s/ulstop
rm -f bin32s/ulsync
rm -f bin32s/ulunload
rm -f bin32s/ulvalid
rm -f bin32s/usm.xsd
rm -f bin32s/viewcert
rm -f bin64/.scRepository*
rm -f bin64/createcert
rm -f bin64/createkey
rm -f bin64/dbbackup
rm -f bin64/dbdsn
rm -f bin64/dbeng12
rm -f bin64/dbeng12.lic
rm -f bin64/dberase
rm -f bin64/dbexternc12
rm -f bin64/dbfhide
rm -f bin64/dbinfo
rm -f bin64/dbinit
rm -f bin64/dbisql_64.rep
rm -f bin64/dbisqlc
rm -f bin64/dblic
rm -f bin64/dblocate
rm -f bin64/dblog
rm -f bin64/dbmlsync
rm -f bin64/dbns12
rm -f bin64/dbping
rm -f bin64/dbremote
rm -f bin64/dbspawn
rm -f bin64/dbsrv12
rm -f bin64/dbsrv12.lic
rm -f bin64/dbstats
rm -f bin64/dbstop
rm -f bin64/dbsupport
rm -f bin64/dbsvc
rm -f bin64/dbsvc_scripts/dbsvc_iface
rm -f bin64/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin64/dbsvc_scripts/dbsvc_iface_rh
rm -f bin64/dbsvc_scripts/dbsvc_iface_suse
rm -f bin64/dbsvc_scripts/distro.sh
rm -f bin64/dbsvc_scripts/svc_functions
rm -f bin64/dbsvc_scripts/svc_t_common
rm -f bin64/dbsvc_scripts/svc_t_dbmlsync
rm -f bin64/dbsvc_scripts/svc_t_dbns
rm -f bin64/dbsvc_scripts/svc_t_dbremote
rm -f bin64/dbsvc_scripts/svc_t_mobilink
rm -f bin64/dbsvc_scripts/svc_t_network
rm -f bin64/dbsvc_scripts/svc_t_personal
rm -f bin64/dbsvc_scripts/svc_t_rshost
rm -f bin64/dbsvc_scripts/svc_t_rsoe
rm -f bin64/dbsvc_scripts/svc_t_standalone
rm -f bin64/dbsvc_scripts/utility.sh
rm -f bin64/dbtran
rm -f bin64/dbtsinfo
rm -f bin64/dbunload
rm -f bin64/dbunlspt
rm -f bin64/dbupgrad
rm -f bin64/dbvalid
rm -f bin64/dbversion
rm -f bin64/dbxtract
rm -f bin64/htmlview
rm -f bin64/language/de/messages.txt
rm -f bin64/language/de/usage.txt
rm -f bin64/language/en/messages.txt
rm -f bin64/language/en/usage.txt
rm -f bin64/language/fr/messages.txt
rm -f bin64/language/fr/usage.txt
rm -f bin64/language/ja/messages.txt
rm -f bin64/language/ja/usage.txt
rm -f bin64/language/zh/messages.txt
rm -f bin64/language/zh/usage.txt
rm -f bin64/mlarb12
rm -f bin64/mlarb12.lic
rm -f bin64/mlarbiter.sh
rm -f bin64/mlfiletransfer
rm -f bin64/mlgenreplayapi
rm -f bin64/mlmon
rm -f bin64/mlreplay
rm -f bin64/mlsrv12
rm -f bin64/mlsrv12.lic
rm -f bin64/mlstop
rm -f bin64/mluser
rm -f bin64/newdemo.sh
rm -f bin64/perlenv.pl
rm -f bin64/phpenv.php
rm -f bin64/rsaroot.crt
rm -f bin64/rsaserver.id
rm -f bin64/rshost
rm -f bin64/rsoe
rm -f bin64/sa_config.csh
rm -f bin64/sa_config.sh
rm -f bin64/sadoc
rm -f bin64/samonitor.sh
rm -f bin64/smstart.dat
rm -f bin64/sqlpp
rm -f bin64/viewcert
rm -f bin64s/createcert
rm -f bin64s/createkey
rm -f bin64s/dbbackup
rm -f bin64s/dbdsn
rm -f bin64s/dbeng12
rm -f bin64s/dberase
rm -f bin64s/dbexternc12
rm -f bin64s/dbfhide
rm -f bin64s/dbinfo
rm -f bin64s/dbinit
rm -f bin64s/dbisqlc
rm -f bin64s/dblic
rm -f bin64s/dblocate
rm -f bin64s/dblog
rm -f bin64s/dbmlsync
rm -f bin64s/dbns12
rm -f bin64s/dbping
rm -f bin64s/dbremote
rm -f bin64s/dbspawn
rm -f bin64s/dbsrv12
rm -f bin64s/dbstats
rm -f bin64s/dbstop
rm -f bin64s/dbsupport
rm -f bin64s/dbsvc
rm -f bin64s/dbsvc_scripts/dbsvc_iface
rm -f bin64s/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin64s/dbsvc_scripts/dbsvc_iface_rh
rm -f bin64s/dbsvc_scripts/dbsvc_iface_suse
rm -f bin64s/dbsvc_scripts/distro.sh
rm -f bin64s/dbsvc_scripts/svc_functions
rm -f bin64s/dbsvc_scripts/svc_t_common
rm -f bin64s/dbsvc_scripts/svc_t_dbmlsync
rm -f bin64s/dbsvc_scripts/svc_t_dbns
rm -f bin64s/dbsvc_scripts/svc_t_dbremote
rm -f bin64s/dbsvc_scripts/svc_t_mobilink
rm -f bin64s/dbsvc_scripts/svc_t_network
rm -f bin64s/dbsvc_scripts/svc_t_personal
rm -f bin64s/dbsvc_scripts/svc_t_rshost
rm -f bin64s/dbsvc_scripts/svc_t_rsoe
rm -f bin64s/dbsvc_scripts/svc_t_standalone
rm -f bin64s/dbsvc_scripts/utility.sh
rm -f bin64s/dbtran
rm -f bin64s/dbtsinfo
rm -f bin64s/dbunload
rm -f bin64s/dbunlspt
rm -f bin64s/dbupgrad
rm -f bin64s/dbvalid
rm -f bin64s/dbversion
rm -f bin64s/dbxtract
rm -f bin64s/htmlview
rm -f bin64s/language/de/messages.txt
rm -f bin64s/language/de/usage.txt
rm -f bin64s/language/en/messages.txt
rm -f bin64s/language/en/usage.txt
rm -f bin64s/language/fr/messages.txt
rm -f bin64s/language/fr/usage.txt
rm -f bin64s/language/ja/messages.txt
rm -f bin64s/language/ja/usage.txt
rm -f bin64s/language/zh/messages.txt
rm -f bin64s/language/zh/usage.txt
rm -f bin64s/mlarb12
rm -f bin64s/mlarb12.lic
rm -f bin64s/mlarbiter.sh
rm -f bin64s/mlfiletransfer
rm -f bin64s/mlgenreplayapi
rm -f bin64s/mlmon
rm -f bin64s/mlreplay
rm -f bin64s/mlsrv12
rm -f bin64s/mlstop
rm -f bin64s/mluser
rm -f bin64s/newdemo.sh
rm -f bin64s/perlenv.pl
rm -f bin64s/phpenv.php
rm -f bin64s/rsaroot.crt
rm -f bin64s/rsaserver.id
rm -f bin64s/rshost
rm -f bin64s/rsoe
rm -f bin64s/sadoc
rm -f bin64s/samonitor.sh
rm -f bin64s/sqlpp
rm -f bin64s/viewcert
rm -f charsets/unicode/big5bin.ust
rm -f charsets/unicode/big5hk.uct
rm -f charsets/unicode/cp037.uct
rm -f charsets/unicode/cp1006.uct
rm -f charsets/unicode/cp1026.uct
rm -f charsets/unicode/cp1140.uct
rm -f charsets/unicode/cp1141.uct
rm -f charsets/unicode/cp1142.uct
rm -f charsets/unicode/cp1143.uct
rm -f charsets/unicode/cp1144.uct
rm -f charsets/unicode/cp1145.uct
rm -f charsets/unicode/cp1146.uct
rm -f charsets/unicode/cp1147.uct
rm -f charsets/unicode/cp1148.uct
rm -f charsets/unicode/cp1149.uct
rm -f charsets/unicode/cp1250.uct
rm -f charsets/unicode/cp1251.uct
rm -f charsets/unicode/cp1252.uct
rm -f charsets/unicode/cp1253.uct
rm -f charsets/unicode/cp1254.uct
rm -f charsets/unicode/cp1255.uct
rm -f charsets/unicode/cp1256.uct
rm -f charsets/unicode/cp1257.uct
rm -f charsets/unicode/cp1258.uct
rm -f charsets/unicode/cp273.uct
rm -f charsets/unicode/cp277.uct
rm -f charsets/unicode/cp278.uct
rm -f charsets/unicode/cp280.uct
rm -f charsets/unicode/cp284.uct
rm -f charsets/unicode/cp285.uct
rm -f charsets/unicode/cp297.uct
rm -f charsets/unicode/cp300.uct
rm -f charsets/unicode/cp424.uct
rm -f charsets/unicode/cp437.uct
rm -f charsets/unicode/cp500.uct
rm -f charsets/unicode/cp737.uct
rm -f charsets/unicode/cp775.uct
rm -f charsets/unicode/cp834.uct
rm -f charsets/unicode/cp835.uct
rm -f charsets/unicode/cp837.uct
rm -f charsets/unicode/cp850.uct
rm -f charsets/unicode/cp852.uct
rm -f charsets/unicode/cp855.uct
rm -f charsets/unicode/cp856.uct
rm -f charsets/unicode/cp857.uct
rm -f charsets/unicode/cp858.uct
rm -f charsets/unicode/cp860.uct
rm -f charsets/unicode/cp861.uct
rm -f charsets/unicode/cp862.uct
rm -f charsets/unicode/cp863.uct
rm -f charsets/unicode/cp864.uct
rm -f charsets/unicode/cp865.uct
rm -f charsets/unicode/cp866.uct
rm -f charsets/unicode/cp869.uct
rm -f charsets/unicode/cp871.uct
rm -f charsets/unicode/cp874.uct
rm -f charsets/unicode/cp874ibm.uct
rm -f charsets/unicode/cp932.uct
rm -f charsets/unicode/cp932bin.ust
rm -f charsets/unicode/cp932ms.uct
rm -f charsets/unicode/cp932ms2.uct
rm -f charsets/unicode/cp932ms3.uct
rm -f charsets/unicode/cp936.uct
rm -f charsets/unicode/cp949.uct
rm -f charsets/unicode/cp950.uct
rm -f charsets/unicode/cyrdict.ust
rm -f charsets/unicode/dynix.ust
rm -f charsets/unicode/euccns.uct
rm -f charsets/unicode/eucgb.uct
rm -f charsets/unicode/eucjisbn.ust
rm -f charsets/unicode/eucksc.uct
rm -f charsets/unicode/euckscbn.ust
rm -f charsets/unicode/gb18030.uct
rm -f charsets/unicode/gb2312bn.ust
rm -f charsets/unicode/gbpinyin.ust
rm -f charsets/unicode/greek8.uct
rm -f charsets/unicode/iso10.uct
rm -f charsets/unicode/iso13.uct
rm -f charsets/unicode/iso14.uct
rm -f charsets/unicode/iso15.uct
rm -f charsets/unicode/iso88592.uct
rm -f charsets/unicode/iso88593.uct
rm -f charsets/unicode/iso88594.uct
rm -f charsets/unicode/iso88595.uct
rm -f charsets/unicode/iso88596.uct
rm -f charsets/unicode/iso88597.uct
rm -f charsets/unicode/iso88598.uct
rm -f charsets/unicode/iso88599.uct
rm -f charsets/unicode/koi8.uct
rm -f charsets/unicode/mac.uct
rm -f charsets/unicode/mac_cyr.uct
rm -f charsets/unicode/mac_ee.uct
rm -f charsets/unicode/mac_euro.uct
rm -f charsets/unicode/mac_grk.uct
rm -f charsets/unicode/macgrk2.uct
rm -f charsets/unicode/macthai.uct
rm -f charsets/unicode/macturk.uct
rm -f charsets/unicode/roman8.uct
rm -f charsets/unicode/roman9.uct
rm -f charsets/unicode/rusdict.ust
rm -f charsets/unicode/sjis.uct
rm -f charsets/unicode/sjisbin.ust
rm -f charsets/unicode/test.ust
rm -f charsets/unicode/tis620.uct
rm -f charsets/unicode/turdict.ust
rm -f charsets/unicode/turkish8.uct
rm -f demo.db
rm -f demo.log
rm -f deployment/bin32/csconvert
rm -f deployment/bin32/dbinstall
rm -f deployment/bin32/gsetup
rm -f deployment/bin32s/csconvert
rm -f deployment/bin32s/dbinstall
rm -f deployment/bin32s/gsetup
rm -f deployment/bin64/csconvert
rm -f deployment/bin64/dbinstall
rm -f deployment/bin64/gsetup
rm -f deployment/bin64s/csconvert
rm -f deployment/bin64s/dbinstall
rm -f deployment/bin64s/gsetup
rm -f deployment/deploy.noarch.tic
rm -f deployment/deployment_wizard.sh
rm -f deployment/lib32/libdbicu12.so
rm -f deployment/lib32/libdbicu12.so.1
rm -f deployment/lib32/libdbicu12_r.so
rm -f deployment/lib32/libdbicu12_r.so.1
rm -f deployment/lib32/libdbtasks12.so
rm -f deployment/lib32/libdbtasks12.so.1
rm -f deployment/lib32/libdbtasks12_r.so
rm -f deployment/lib32/libdbtasks12_r.so.1
rm -f deployment/lib64/libdbicu12.so
rm -f deployment/lib64/libdbicu12.so.1
rm -f deployment/lib64/libdbicu12_r.so
rm -f deployment/lib64/libdbicu12_r.so.1
rm -f deployment/lib64/libdbtasks12.so
rm -f deployment/lib64/libdbtasks12.so.1
rm -f deployment/lib64/libdbtasks12_r.so
rm -f deployment/lib64/libdbtasks12_r.so.1
rm -f deployment/res/dbicudt12.dat
rm -f deployment/res/language/all_langs_icon_resources_utf8.txt
rm -f deployment/res/language/common.sh
rm -f deployment/res/language/de/messages.txt
rm -f deployment/res/language/en/messages.txt
rm -f deployment/res/language/fr/messages.txt
rm -f deployment/res/language/ja/messages.txt
rm -f deployment/res/language/zh/messages.txt
rm -f deployment/res/scripts/array.sh
rm -f deployment/res/scripts/checkupdates.sh
rm -f deployment/res/scripts/cleanup.sh
rm -f deployment/res/scripts/client_flow.sh
rm -f deployment/res/scripts/cmdline.sh
rm -f deployment/res/scripts/component_spt.sh
rm -f deployment/res/scripts/config.sh
rm -f deployment/res/scripts/console_ui.sh
rm -f deployment/res/scripts/csconvert.sh
rm -f deployment/res/scripts/csh_support.sh
rm -f deployment/res/scripts/dbcloud.sh
rm -f deployment/res/scripts/dbcloud_flow.sh
rm -f deployment/res/scripts/deploy_flow.sh
rm -f deployment/res/scripts/deploy_wizard.sh
rm -f deployment/res/scripts/directory.sh
rm -f deployment/res/scripts/diskspace.sh
rm -f deployment/res/scripts/distro.sh
rm -f deployment/res/scripts/doc_flow.sh
rm -f deployment/res/scripts/generated.sh
rm -f deployment/res/scripts/installicon.sh
rm -f deployment/res/scripts/interactive_ui.sh
rm -f deployment/res/scripts/language.sh
rm -f deployment/res/scripts/license.sh
rm -f deployment/res/scripts/licenser_flow.sh
rm -f deployment/res/scripts/links.sh
rm -f deployment/res/scripts/options.sh
rm -f deployment/res/scripts/os.sh
rm -f deployment/res/scripts/package.sh
rm -f deployment/res/scripts/panel.sh
rm -f deployment/res/scripts/platform.sh
rm -f deployment/res/scripts/populate_menus.sh
rm -f deployment/res/scripts/registration.sh
rm -f deployment/res/scripts/rollback.sh
rm -f deployment/res/scripts/runinstall.sh
rm -f deployment/res/scripts/samon.sh
rm -f deployment/res/scripts/samon_flow.sh
rm -f deployment/res/scripts/sh_support.sh
rm -f deployment/res/scripts/shortcuts.sh
rm -f deployment/res/scripts/sighndlr.sh
rm -f deployment/res/scripts/silent_ui.sh
rm -f deployment/res/scripts/standard_flow.sh
rm -f deployment/res/scripts/summary.sh
rm -f deployment/res/scripts/ui.sh
rm -f deployment/res/scripts/upgrade.sh
rm -f deployment/res/scripts/user.sh
rm -f deployment/res/scripts/utility.sh
rm -f deployment/res/scripts/versioning.sh
rm -f documentation/de/version.txt
rm -f documentation/eclipse/plugins/com.sybase.help.sqlanywhere.nl.de_12.0.1.jar
rm -f documentation/eclipse/plugins/com.sybase.help.sqlanywhere.nl.ja_12.0.1.jar
rm -f documentation/eclipse/plugins/com.sybase.help.sqlanywhere.nl.zh_12.0.1.jar
rm -f documentation/eclipse/plugins/com.sybase.help.sqlanywhere_12.0.1.jar
rm -f documentation/en/components_platforms.html
rm -f documentation/en/ianywhere.html
rm -f documentation/en/listener.html
rm -f documentation/en/pdf/sqlremote12.pdf
rm -f documentation/en/redirector_web_servers.html
rm -f documentation/en/resources.gif
rm -f documentation/en/supported_kerberos_clients.html
rm -f documentation/en/supported_platforms.html
rm -f documentation/en/supported_platforms_sa_linux.html
rm -f documentation/en/version.txt
rm -f documentation/ja/version.txt
rm -f documentation/sqlanywhere_de12.map
rm -f documentation/sqlanywhere_en12.map
rm -f documentation/sqlanywhere_ja12.map
rm -f documentation/sqlanywhere_zh12.map
rm -f documentation/zh/version.txt
rm -f install_*.log
rm -f installed.ini
rm -f java/*.jpr
rm -f java/DBConsole.jar
rm -f java/JComponents1200.jar
rm -f java/JComponents1201.jar
rm -f java/SCEditor610.jar
rm -f java/activation.jar
rm -f java/apache_files.txt
rm -f java/apache_license_1.1.txt
rm -f java/apache_license_2.0.txt
rm -f java/batik-anim.jar
rm -f java/batik-awt-util.jar
rm -f java/batik-bridge.jar
rm -f java/batik-codec.jar
rm -f java/batik-css.jar
rm -f java/batik-dom.jar
rm -f java/batik-ext.jar
rm -f java/batik-extension.jar
rm -f java/batik-gui-util.jar
rm -f java/batik-gvt.jar
rm -f java/batik-parser.jar
rm -f java/batik-script.jar
rm -f java/batik-svg-dom.jar
rm -f java/batik-svggen.jar
rm -f java/batik-swing.jar
rm -f java/batik-transcoder.jar
rm -f java/batik-util.jar
rm -f java/batik-xml.jar
rm -f java/cis.zip
rm -f java/commons-codec-1.3.jar
rm -f java/commons-httpclient-3.0.jar
rm -f java/commons-logging.jar
rm -f java/dbdiff.jar
rm -f java/debugger.jar
rm -f java/diffutils-1.2.1.jar
rm -f java/imap.jar
rm -f java/isql.jar
rm -f java/jconn3.jar
rm -f java/jlogon.jar
rm -f java/jodbc.jar
rm -f java/jodbc4.jar
rm -f java/js.jar
rm -f java/jsyblib610.jar
rm -f java/mailapi.jar
rm -f java/migrator.jar
rm -f java/ml-templates.zip
rm -f java/mldesign.jar
rm -f java/mlmon.jar
rm -f java/mlnotif.jar
rm -f java/mlplugin.jar
rm -f java/mlscript.jar
rm -f java/mlstream.jar
rm -f java/mlsupport.jar
rm -f java/pdf-transcoder.jar
rm -f java/pop3.jar
rm -f java/qaconnector.jar
rm -f java/qaplugin.jar
rm -f java/qastandaloneclient.jar
rm -f java/rsplugin.jar
rm -f java/rstool.jar
rm -f java/sa_java.sh
rm -f java/saip12.jar
rm -f java/sajdbc.jar
rm -f java/sajdbc4.jar
rm -f java/sajvm.jar
rm -f java/salib.jar
rm -f java/samonlauncher.jar
rm -f java/saplugin.jar
rm -f java/smtp.jar
rm -f java/stax-api-1.0.jar
rm -f java/sybasecentral610.jar
rm -f java/ulplugin.jar
rm -f java/velocity-dep.jar
rm -f java/velocity.jar
rm -f java/wstx-asl-2.0.5.jar
rm -f java/wstx-asl-3.2.6.jar
rm -f java/xalan-2.6.0.jar
rm -f java/xerces_2_5_0.jar
rm -f java/xml-apis-ext.jar
rm -f java/xml-apis.jar
rm -f lib32/libcrypto.so
rm -f lib32/libcrypto.so.1.0.0
rm -f lib32/libdbcapi.so
rm -f lib32/libdbcapi.so.1
rm -f lib32/libdbcapi_r.so
rm -f lib32/libdbcapi_r.so.1
rm -f lib32/libdbcis12.so
rm -f lib32/libdbcis12.so.1
rm -f lib32/libdbencod12_r.so
rm -f lib32/libdbencod12_r.so.1
rm -f lib32/libdbextenv12_r.so
rm -f lib32/libdbextenv12_r.so.1
rm -f lib32/libdbextf.so
rm -f lib32/libdbextf.so.1
rm -f lib32/libdbfile12_r.so
rm -f lib32/libdbfile12_r.so.1
rm -f lib32/libdbfips12.so
rm -f lib32/libdbfips12.so.1
rm -f lib32/libdbfips12_r.so
rm -f lib32/libdbfips12_r.so.1
rm -f lib32/libdbftp12_r.so
rm -f lib32/libdbftp12_r.so.1
rm -f lib32/libdbhttp12_r.so
rm -f lib32/libdbhttp12_r.so.1
rm -f lib32/libdbicu12.so
rm -f lib32/libdbicu12.so.1
rm -f lib32/libdbicu12_r.so
rm -f lib32/libdbicu12_r.so.1
rm -f lib32/libdbicudt12.so
rm -f lib32/libdbicudt12.so.1
rm -f lib32/libdbjdbc12.so
rm -f lib32/libdbjdbc12.so.1
rm -f lib32/libdbjodbc12.so
rm -f lib32/libdbjodbc12.so.1
rm -f lib32/libdblaiod12.so
rm -f lib32/libdblaiod12.so.1
rm -f lib32/libdblib12.so
rm -f lib32/libdblib12.so.1
rm -f lib32/libdblib12_r.so
rm -f lib32/libdblib12_r.so.1
rm -f lib32/libdbmlsynccli12_r.so
rm -f lib32/libdbmlsynccli12_r.so.1
rm -f lib32/libdbodbc12.so
rm -f lib32/libdbodbc12.so.1
rm -f lib32/libdbodbc12_n.so
rm -f lib32/libdbodbc12_n.so.1
rm -f lib32/libdbodbc12_r.so
rm -f lib32/libdbodbc12_r.so.1
rm -f lib32/libdbodbcansi12_r.so
rm -f lib32/libdbodbcansi12_r.so.1
rm -f lib32/libdbodbcinst12_r.so
rm -f lib32/libdbodbcinst12_r.so.1
rm -f lib32/libdbodm12.so
rm -f lib32/libdbodm12.so.1
rm -f lib32/libdboftsp_r.so
rm -f lib32/libdboftsp_r.so.1
rm -f lib32/libdboraodbc12_r.so
rm -f lib32/libdboraodbc12_r.so.1
rm -f lib32/libdbperfapi12_r.so
rm -f lib32/libdbperfapi12_r.so.1
rm -f lib32/libdbput12_r.so
rm -f lib32/libdbput12_r.so.1
rm -f lib32/libdbrsa12.so
rm -f lib32/libdbrsa12.so.1
rm -f lib32/libdbrsa12_r.so
rm -f lib32/libdbrsa12_r.so.1
rm -f lib32/libdbrsakp12_r.so
rm -f lib32/libdbrsakp12_r.so.1
rm -f lib32/libdbscript12_r.so
rm -f lib32/libdbscript12_r.so.1
rm -f lib32/libdbserv12_r.so
rm -f lib32/libdbserv12_r.so.1
rm -f lib32/libdbsmtp12_r.so
rm -f lib32/libdbsmtp12_r.so.1
rm -f lib32/libdbsrvmon12_r.so
rm -f lib32/libdbsrvmon12_r.so.1
rm -f lib32/libdbtasks12.so
rm -f lib32/libdbtasks12.so.1
rm -f lib32/libdbtasks12_r.so
rm -f lib32/libdbtasks12_r.so.1
rm -f lib32/libdbtool12_r.so
rm -f lib32/libdbtool12_r.so.1
rm -f lib32/libdbxgtk12_r.so
rm -f lib32/libdbxgtk12_r.so.1
rm -f lib32/libjsyblib610_r.so
rm -f lib32/libjsyblib610_r.so.1
rm -f lib32/libmlcrsa12_r.so
rm -f lib32/libmlcrsa12_r.so.1
rm -f lib32/libmlcrsafips12_r.so
rm -f lib32/libmlcrsafips12_r.so.1
rm -f lib32/libmlczlib12_r.so
rm -f lib32/libmlczlib12_r.so.1
rm -f lib32/libmlhttp12_r.so
rm -f lib32/libmlhttp12_r.so.1
rm -f lib32/libmljava12_r.so
rm -f lib32/libmljava12_r.so.1
rm -f lib32/libmljodbc12.so
rm -f lib32/libmljodbc12.so.1
rm -f lib32/libmljstrm12_r.so
rm -f lib32/libmljstrm12_r.so.1
rm -f lib32/libmlodbc12_r.so
rm -f lib32/libmlodbc12_r.so.1
rm -f lib32/libmlreplaylib_r.so
rm -f lib32/libmlreplaylib_r.so.1
rm -f lib32/libmlrsa_tls12_r.so
rm -f lib32/libmlrsa_tls12_r.so.1
rm -f lib32/libmlrsa_tls_fips12_r.so
rm -f lib32/libmlrsa_tls_fips12_r.so.1
rm -f lib32/libmlsock12_r.so
rm -f lib32/libmlsock12_r.so.1
rm -f lib32/libmlsql12_r.so
rm -f lib32/libmlsql12_r.so.1
rm -f lib32/libodbcinst.so
rm -f lib32/libodbcinst.so.1
rm -f lib32/libqadbiulsjni12_r.so
rm -f lib32/libqadbiulsjni12_r.so.1
rm -f lib32/librsoesupp12_r.so
rm -f lib32/librsoesupp12_r.so.1
rm -f lib32/libssl.so
rm -f lib32/libssl.so.1.0.0
rm -f lib32/libsybbr.so
rm -f lib32/libsybbr.so.1
rm -f lib32/libulodbc12_r.so
rm -f lib32/libulodbc12_r.so.1
rm -f lib32/libulscutil12.so
rm -f lib32/libulscutil12.so.1
rm -f lib32/libulutils12_r.so
rm -f lib32/libulutils12_r.so.1
rm -f lib32/php-5.1.1_sqlanywhere.so
rm -f lib32/php-5.1.1_sqlanywhere.so.1
rm -f lib32/php-5.1.1_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.1_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.1_sqlanywhere_r.so
rm -f lib32/php-5.1.1_sqlanywhere_r.so.1
rm -f lib32/php-5.1.2_sqlanywhere.so
rm -f lib32/php-5.1.2_sqlanywhere.so.1
rm -f lib32/php-5.1.2_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.2_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.2_sqlanywhere_r.so
rm -f lib32/php-5.1.2_sqlanywhere_r.so.1
rm -f lib32/php-5.1.3_sqlanywhere.so
rm -f lib32/php-5.1.3_sqlanywhere.so.1
rm -f lib32/php-5.1.3_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.3_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.3_sqlanywhere_r.so
rm -f lib32/php-5.1.3_sqlanywhere_r.so.1
rm -f lib32/php-5.1.4_sqlanywhere.so
rm -f lib32/php-5.1.4_sqlanywhere.so.1
rm -f lib32/php-5.1.4_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.4_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.4_sqlanywhere_r.so
rm -f lib32/php-5.1.4_sqlanywhere_r.so.1
rm -f lib32/php-5.1.5_sqlanywhere.so
rm -f lib32/php-5.1.5_sqlanywhere.so.1
rm -f lib32/php-5.1.5_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.5_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.5_sqlanywhere_r.so
rm -f lib32/php-5.1.5_sqlanywhere_r.so.1
rm -f lib32/php-5.1.6_sqlanywhere.so
rm -f lib32/php-5.1.6_sqlanywhere.so.1
rm -f lib32/php-5.1.6_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.1.6_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.1.6_sqlanywhere_r.so
rm -f lib32/php-5.1.6_sqlanywhere_r.so.1
rm -f lib32/php-5.2.0_sqlanywhere.so
rm -f lib32/php-5.2.0_sqlanywhere.so.1
rm -f lib32/php-5.2.0_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.0_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.0_sqlanywhere_r.so
rm -f lib32/php-5.2.0_sqlanywhere_r.so.1
rm -f lib32/php-5.2.10_sqlanywhere.so
rm -f lib32/php-5.2.10_sqlanywhere.so.1
rm -f lib32/php-5.2.10_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.10_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.10_sqlanywhere_r.so
rm -f lib32/php-5.2.10_sqlanywhere_r.so.1
rm -f lib32/php-5.2.11_sqlanywhere.so
rm -f lib32/php-5.2.11_sqlanywhere.so.1
rm -f lib32/php-5.2.11_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.11_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.11_sqlanywhere_r.so
rm -f lib32/php-5.2.11_sqlanywhere_r.so.1
rm -f lib32/php-5.2.12_sqlanywhere.so
rm -f lib32/php-5.2.12_sqlanywhere.so.1
rm -f lib32/php-5.2.12_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.12_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.12_sqlanywhere_r.so
rm -f lib32/php-5.2.12_sqlanywhere_r.so.1
rm -f lib32/php-5.2.13_sqlanywhere.so
rm -f lib32/php-5.2.13_sqlanywhere.so.1
rm -f lib32/php-5.2.13_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.13_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.13_sqlanywhere_r.so
rm -f lib32/php-5.2.13_sqlanywhere_r.so.1
rm -f lib32/php-5.2.14_sqlanywhere.so
rm -f lib32/php-5.2.14_sqlanywhere.so.1
rm -f lib32/php-5.2.14_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.14_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.14_sqlanywhere_r.so
rm -f lib32/php-5.2.14_sqlanywhere_r.so.1
rm -f lib32/php-5.2.15_sqlanywhere.so
rm -f lib32/php-5.2.15_sqlanywhere.so.1
rm -f lib32/php-5.2.15_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.15_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.15_sqlanywhere_r.so
rm -f lib32/php-5.2.15_sqlanywhere_r.so.1
rm -f lib32/php-5.2.16_sqlanywhere.so
rm -f lib32/php-5.2.16_sqlanywhere.so.1
rm -f lib32/php-5.2.16_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.16_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.16_sqlanywhere_r.so
rm -f lib32/php-5.2.16_sqlanywhere_r.so.1
rm -f lib32/php-5.2.17_sqlanywhere.so
rm -f lib32/php-5.2.17_sqlanywhere.so.1
rm -f lib32/php-5.2.17_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.17_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.17_sqlanywhere_r.so
rm -f lib32/php-5.2.17_sqlanywhere_r.so.1
rm -f lib32/php-5.2.1_sqlanywhere.so
rm -f lib32/php-5.2.1_sqlanywhere.so.1
rm -f lib32/php-5.2.1_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.1_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.1_sqlanywhere_r.so
rm -f lib32/php-5.2.1_sqlanywhere_r.so.1
rm -f lib32/php-5.2.2_sqlanywhere.so
rm -f lib32/php-5.2.2_sqlanywhere.so.1
rm -f lib32/php-5.2.2_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.2_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.2_sqlanywhere_r.so
rm -f lib32/php-5.2.2_sqlanywhere_r.so.1
rm -f lib32/php-5.2.3_sqlanywhere.so
rm -f lib32/php-5.2.3_sqlanywhere.so.1
rm -f lib32/php-5.2.3_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.3_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.3_sqlanywhere_r.so
rm -f lib32/php-5.2.3_sqlanywhere_r.so.1
rm -f lib32/php-5.2.4_sqlanywhere.so
rm -f lib32/php-5.2.4_sqlanywhere.so.1
rm -f lib32/php-5.2.4_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.4_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.4_sqlanywhere_r.so
rm -f lib32/php-5.2.4_sqlanywhere_r.so.1
rm -f lib32/php-5.2.5_sqlanywhere.so
rm -f lib32/php-5.2.5_sqlanywhere.so.1
rm -f lib32/php-5.2.5_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.5_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.5_sqlanywhere_r.so
rm -f lib32/php-5.2.5_sqlanywhere_r.so.1
rm -f lib32/php-5.2.6_sqlanywhere.so
rm -f lib32/php-5.2.6_sqlanywhere.so.1
rm -f lib32/php-5.2.6_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.6_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.6_sqlanywhere_r.so
rm -f lib32/php-5.2.6_sqlanywhere_r.so.1
rm -f lib32/php-5.2.8_sqlanywhere.so
rm -f lib32/php-5.2.8_sqlanywhere.so.1
rm -f lib32/php-5.2.8_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.8_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.8_sqlanywhere_r.so
rm -f lib32/php-5.2.8_sqlanywhere_r.so.1
rm -f lib32/php-5.2.9_sqlanywhere.so
rm -f lib32/php-5.2.9_sqlanywhere.so.1
rm -f lib32/php-5.2.9_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.2.9_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.2.9_sqlanywhere_r.so
rm -f lib32/php-5.2.9_sqlanywhere_r.so.1
rm -f lib32/php-5.3.0_sqlanywhere.so
rm -f lib32/php-5.3.0_sqlanywhere.so.1
rm -f lib32/php-5.3.0_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.0_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.0_sqlanywhere_r.so
rm -f lib32/php-5.3.0_sqlanywhere_r.so.1
rm -f lib32/php-5.3.10_sqlanywhere.so
rm -f lib32/php-5.3.10_sqlanywhere.so.1
rm -f lib32/php-5.3.10_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.10_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.10_sqlanywhere_r.so
rm -f lib32/php-5.3.10_sqlanywhere_r.so.1
rm -f lib32/php-5.3.11_sqlanywhere.so
rm -f lib32/php-5.3.11_sqlanywhere.so.1
rm -f lib32/php-5.3.11_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.11_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.11_sqlanywhere_r.so
rm -f lib32/php-5.3.11_sqlanywhere_r.so.1
rm -f lib32/php-5.3.12_sqlanywhere.so
rm -f lib32/php-5.3.12_sqlanywhere.so.1
rm -f lib32/php-5.3.12_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.12_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.12_sqlanywhere_r.so
rm -f lib32/php-5.3.12_sqlanywhere_r.so.1
rm -f lib32/php-5.3.13_sqlanywhere.so
rm -f lib32/php-5.3.13_sqlanywhere.so.1
rm -f lib32/php-5.3.13_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.13_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.13_sqlanywhere_r.so
rm -f lib32/php-5.3.13_sqlanywhere_r.so.1
rm -f lib32/php-5.3.14_sqlanywhere.so
rm -f lib32/php-5.3.14_sqlanywhere.so.1
rm -f lib32/php-5.3.14_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.14_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.14_sqlanywhere_r.so
rm -f lib32/php-5.3.14_sqlanywhere_r.so.1
rm -f lib32/php-5.3.15_sqlanywhere.so
rm -f lib32/php-5.3.15_sqlanywhere.so.1
rm -f lib32/php-5.3.15_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.15_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.15_sqlanywhere_r.so
rm -f lib32/php-5.3.15_sqlanywhere_r.so.1
rm -f lib32/php-5.3.16_sqlanywhere.so
rm -f lib32/php-5.3.16_sqlanywhere.so.1
rm -f lib32/php-5.3.16_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.16_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.16_sqlanywhere_r.so
rm -f lib32/php-5.3.16_sqlanywhere_r.so.1
rm -f lib32/php-5.3.17_sqlanywhere.so
rm -f lib32/php-5.3.17_sqlanywhere.so.1
rm -f lib32/php-5.3.17_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.17_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.17_sqlanywhere_r.so
rm -f lib32/php-5.3.17_sqlanywhere_r.so.1
rm -f lib32/php-5.3.18_sqlanywhere.so
rm -f lib32/php-5.3.18_sqlanywhere.so.1
rm -f lib32/php-5.3.18_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.18_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.18_sqlanywhere_r.so
rm -f lib32/php-5.3.18_sqlanywhere_r.so.1
rm -f lib32/php-5.3.19_sqlanywhere.so
rm -f lib32/php-5.3.19_sqlanywhere.so.1
rm -f lib32/php-5.3.19_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.19_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.19_sqlanywhere_r.so
rm -f lib32/php-5.3.19_sqlanywhere_r.so.1
rm -f lib32/php-5.3.1_sqlanywhere.so
rm -f lib32/php-5.3.1_sqlanywhere.so.1
rm -f lib32/php-5.3.1_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.1_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.1_sqlanywhere_r.so
rm -f lib32/php-5.3.1_sqlanywhere_r.so.1
rm -f lib32/php-5.3.20_sqlanywhere.so
rm -f lib32/php-5.3.20_sqlanywhere.so.1
rm -f lib32/php-5.3.20_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.20_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.20_sqlanywhere_r.so
rm -f lib32/php-5.3.20_sqlanywhere_r.so.1
rm -f lib32/php-5.3.21_sqlanywhere.so
rm -f lib32/php-5.3.21_sqlanywhere.so.1
rm -f lib32/php-5.3.21_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.21_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.21_sqlanywhere_r.so
rm -f lib32/php-5.3.21_sqlanywhere_r.so.1
rm -f lib32/php-5.3.22_sqlanywhere.so
rm -f lib32/php-5.3.22_sqlanywhere.so.1
rm -f lib32/php-5.3.22_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.22_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.22_sqlanywhere_r.so
rm -f lib32/php-5.3.22_sqlanywhere_r.so.1
rm -f lib32/php-5.3.23_sqlanywhere.so
rm -f lib32/php-5.3.23_sqlanywhere.so.1
rm -f lib32/php-5.3.23_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.23_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.23_sqlanywhere_r.so
rm -f lib32/php-5.3.23_sqlanywhere_r.so.1
rm -f lib32/php-5.3.24_sqlanywhere.so
rm -f lib32/php-5.3.24_sqlanywhere.so.1
rm -f lib32/php-5.3.24_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.24_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.24_sqlanywhere_r.so
rm -f lib32/php-5.3.24_sqlanywhere_r.so.1
rm -f lib32/php-5.3.25_sqlanywhere.so
rm -f lib32/php-5.3.25_sqlanywhere.so.1
rm -f lib32/php-5.3.25_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.25_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.25_sqlanywhere_r.so
rm -f lib32/php-5.3.25_sqlanywhere_r.so.1
rm -f lib32/php-5.3.26_sqlanywhere.so
rm -f lib32/php-5.3.26_sqlanywhere.so.1
rm -f lib32/php-5.3.26_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.26_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.26_sqlanywhere_r.so
rm -f lib32/php-5.3.26_sqlanywhere_r.so.1
rm -f lib32/php-5.3.2_sqlanywhere.so
rm -f lib32/php-5.3.2_sqlanywhere.so.1
rm -f lib32/php-5.3.2_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.2_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.2_sqlanywhere_r.so
rm -f lib32/php-5.3.2_sqlanywhere_r.so.1
rm -f lib32/php-5.3.3_sqlanywhere.so
rm -f lib32/php-5.3.3_sqlanywhere.so.1
rm -f lib32/php-5.3.3_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.3_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.3_sqlanywhere_r.so
rm -f lib32/php-5.3.3_sqlanywhere_r.so.1
rm -f lib32/php-5.3.4_sqlanywhere.so
rm -f lib32/php-5.3.4_sqlanywhere.so.1
rm -f lib32/php-5.3.4_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.4_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.4_sqlanywhere_r.so
rm -f lib32/php-5.3.4_sqlanywhere_r.so.1
rm -f lib32/php-5.3.5_sqlanywhere.so
rm -f lib32/php-5.3.5_sqlanywhere.so.1
rm -f lib32/php-5.3.5_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.5_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.5_sqlanywhere_r.so
rm -f lib32/php-5.3.5_sqlanywhere_r.so.1
rm -f lib32/php-5.3.6_sqlanywhere.so
rm -f lib32/php-5.3.6_sqlanywhere.so.1
rm -f lib32/php-5.3.6_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.6_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.6_sqlanywhere_r.so
rm -f lib32/php-5.3.6_sqlanywhere_r.so.1
rm -f lib32/php-5.3.7_sqlanywhere.so
rm -f lib32/php-5.3.7_sqlanywhere.so.1
rm -f lib32/php-5.3.7_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.7_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.7_sqlanywhere_r.so
rm -f lib32/php-5.3.7_sqlanywhere_r.so.1
rm -f lib32/php-5.3.8_sqlanywhere.so
rm -f lib32/php-5.3.8_sqlanywhere.so.1
rm -f lib32/php-5.3.8_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.8_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.8_sqlanywhere_r.so
rm -f lib32/php-5.3.8_sqlanywhere_r.so.1
rm -f lib32/php-5.3.9_sqlanywhere.so
rm -f lib32/php-5.3.9_sqlanywhere.so.1
rm -f lib32/php-5.3.9_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.3.9_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.3.9_sqlanywhere_r.so
rm -f lib32/php-5.3.9_sqlanywhere_r.so.1
rm -f lib32/php-5.4.0_sqlanywhere.so
rm -f lib32/php-5.4.0_sqlanywhere.so.1
rm -f lib32/php-5.4.0_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.0_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.0_sqlanywhere_r.so
rm -f lib32/php-5.4.0_sqlanywhere_r.so.1
rm -f lib32/php-5.4.10_sqlanywhere.so
rm -f lib32/php-5.4.10_sqlanywhere.so.1
rm -f lib32/php-5.4.10_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.10_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.10_sqlanywhere_r.so
rm -f lib32/php-5.4.10_sqlanywhere_r.so.1
rm -f lib32/php-5.4.11_sqlanywhere.so
rm -f lib32/php-5.4.11_sqlanywhere.so.1
rm -f lib32/php-5.4.11_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.11_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.11_sqlanywhere_r.so
rm -f lib32/php-5.4.11_sqlanywhere_r.so.1
rm -f lib32/php-5.4.12_sqlanywhere.so
rm -f lib32/php-5.4.12_sqlanywhere.so.1
rm -f lib32/php-5.4.12_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.12_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.12_sqlanywhere_r.so
rm -f lib32/php-5.4.12_sqlanywhere_r.so.1
rm -f lib32/php-5.4.13_sqlanywhere.so
rm -f lib32/php-5.4.13_sqlanywhere.so.1
rm -f lib32/php-5.4.13_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.13_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.13_sqlanywhere_r.so
rm -f lib32/php-5.4.13_sqlanywhere_r.so.1
rm -f lib32/php-5.4.14_sqlanywhere.so
rm -f lib32/php-5.4.14_sqlanywhere.so.1
rm -f lib32/php-5.4.14_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.14_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.14_sqlanywhere_r.so
rm -f lib32/php-5.4.14_sqlanywhere_r.so.1
rm -f lib32/php-5.4.15_sqlanywhere.so
rm -f lib32/php-5.4.15_sqlanywhere.so.1
rm -f lib32/php-5.4.15_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.15_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.15_sqlanywhere_r.so
rm -f lib32/php-5.4.15_sqlanywhere_r.so.1
rm -f lib32/php-5.4.16_sqlanywhere.so
rm -f lib32/php-5.4.16_sqlanywhere.so.1
rm -f lib32/php-5.4.16_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.16_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.16_sqlanywhere_r.so
rm -f lib32/php-5.4.16_sqlanywhere_r.so.1
rm -f lib32/php-5.4.1_sqlanywhere.so
rm -f lib32/php-5.4.1_sqlanywhere.so.1
rm -f lib32/php-5.4.1_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.1_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.1_sqlanywhere_r.so
rm -f lib32/php-5.4.1_sqlanywhere_r.so.1
rm -f lib32/php-5.4.2_sqlanywhere.so
rm -f lib32/php-5.4.2_sqlanywhere.so.1
rm -f lib32/php-5.4.2_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.2_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.2_sqlanywhere_r.so
rm -f lib32/php-5.4.2_sqlanywhere_r.so.1
rm -f lib32/php-5.4.3_sqlanywhere.so
rm -f lib32/php-5.4.3_sqlanywhere.so.1
rm -f lib32/php-5.4.3_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.3_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.3_sqlanywhere_r.so
rm -f lib32/php-5.4.3_sqlanywhere_r.so.1
rm -f lib32/php-5.4.4_sqlanywhere.so
rm -f lib32/php-5.4.4_sqlanywhere.so.1
rm -f lib32/php-5.4.4_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.4_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.4_sqlanywhere_r.so
rm -f lib32/php-5.4.4_sqlanywhere_r.so.1
rm -f lib32/php-5.4.5_sqlanywhere.so
rm -f lib32/php-5.4.5_sqlanywhere.so.1
rm -f lib32/php-5.4.5_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.5_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.5_sqlanywhere_r.so
rm -f lib32/php-5.4.5_sqlanywhere_r.so.1
rm -f lib32/php-5.4.6_sqlanywhere.so
rm -f lib32/php-5.4.6_sqlanywhere.so.1
rm -f lib32/php-5.4.6_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.6_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.6_sqlanywhere_r.so
rm -f lib32/php-5.4.6_sqlanywhere_r.so.1
rm -f lib32/php-5.4.7_sqlanywhere.so
rm -f lib32/php-5.4.7_sqlanywhere.so.1
rm -f lib32/php-5.4.7_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.7_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.7_sqlanywhere_r.so
rm -f lib32/php-5.4.7_sqlanywhere_r.so.1
rm -f lib32/php-5.4.8_sqlanywhere.so
rm -f lib32/php-5.4.8_sqlanywhere.so.1
rm -f lib32/php-5.4.8_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.8_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.8_sqlanywhere_r.so
rm -f lib32/php-5.4.8_sqlanywhere_r.so.1
rm -f lib32/php-5.4.9_sqlanywhere.so
rm -f lib32/php-5.4.9_sqlanywhere.so.1
rm -f lib32/php-5.4.9_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.4.9_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.4.9_sqlanywhere_r.so
rm -f lib32/php-5.4.9_sqlanywhere_r.so.1
rm -f lib32/php-5.5.0_sqlanywhere.so
rm -f lib32/php-5.5.0_sqlanywhere.so.1
rm -f lib32/php-5.5.0_sqlanywhere_extenv12_r.so
rm -f lib32/php-5.5.0_sqlanywhere_extenv12_r.so.1
rm -f lib32/php-5.5.0_sqlanywhere_r.so
rm -f lib32/php-5.5.0_sqlanywhere_r.so.1
rm -f lib64/libcrypto.so
rm -f lib64/libcrypto.so.1.0.0
rm -f lib64/libdbcapi.so
rm -f lib64/libdbcapi.so.1
rm -f lib64/libdbcapi_r.so
rm -f lib64/libdbcapi_r.so.1
rm -f lib64/libdbcis12.so
rm -f lib64/libdbcis12.so.1
rm -f lib64/libdbencod12_r.so
rm -f lib64/libdbencod12_r.so.1
rm -f lib64/libdbextenv12_r.so
rm -f lib64/libdbextenv12_r.so.1
rm -f lib64/libdbextf.so
rm -f lib64/libdbextf.so.1
rm -f lib64/libdbfile12_r.so
rm -f lib64/libdbfile12_r.so.1
rm -f lib64/libdbfips12.so
rm -f lib64/libdbfips12.so.1
rm -f lib64/libdbfips12_r.so
rm -f lib64/libdbfips12_r.so.1
rm -f lib64/libdbftp12_r.so
rm -f lib64/libdbftp12_r.so.1
rm -f lib64/libdbhttp12_r.so
rm -f lib64/libdbhttp12_r.so.1
rm -f lib64/libdbicu12.so
rm -f lib64/libdbicu12.so.1
rm -f lib64/libdbicu12_r.so
rm -f lib64/libdbicu12_r.so.1
rm -f lib64/libdbicudt12.so
rm -f lib64/libdbicudt12.so.1
rm -f lib64/libdbjdbc12.so
rm -f lib64/libdbjdbc12.so.1
rm -f lib64/libdbjodbc12.so
rm -f lib64/libdbjodbc12.so.1
rm -f lib64/libdblaiod12.so
rm -f lib64/libdblaiod12.so.1
rm -f lib64/libdblib12.so
rm -f lib64/libdblib12.so.1
rm -f lib64/libdblib12_r.so
rm -f lib64/libdblib12_r.so.1
rm -f lib64/libdbmlsynccli12_r.so
rm -f lib64/libdbmlsynccli12_r.so.1
rm -f lib64/libdbodbc12.so
rm -f lib64/libdbodbc12.so.1
rm -f lib64/libdbodbc12_n.so
rm -f lib64/libdbodbc12_n.so.1
rm -f lib64/libdbodbc12_r.so
rm -f lib64/libdbodbc12_r.so.1
rm -f lib64/libdbodbcansi12_r.so
rm -f lib64/libdbodbcansi12_r.so.1
rm -f lib64/libdbodbcinst12_r.so
rm -f lib64/libdbodbcinst12_r.so.1
rm -f lib64/libdbodm12.so
rm -f lib64/libdbodm12.so.1
rm -f lib64/libdboftsp_r.so
rm -f lib64/libdboftsp_r.so.1
rm -f lib64/libdboraodbc12_r.so
rm -f lib64/libdboraodbc12_r.so.1
rm -f lib64/libdbperfapi12_r.so
rm -f lib64/libdbperfapi12_r.so.1
rm -f lib64/libdbrsa12.so
rm -f lib64/libdbrsa12.so.1
rm -f lib64/libdbrsa12_r.so
rm -f lib64/libdbrsa12_r.so.1
rm -f lib64/libdbrsakp12_r.so
rm -f lib64/libdbrsakp12_r.so.1
rm -f lib64/libdbscript12_r.so
rm -f lib64/libdbscript12_r.so.1
rm -f lib64/libdbserv12_r.so
rm -f lib64/libdbserv12_r.so.1
rm -f lib64/libdbsmtp12_r.so
rm -f lib64/libdbsmtp12_r.so.1
rm -f lib64/libdbsrvmon12_r.so
rm -f lib64/libdbsrvmon12_r.so.1
rm -f lib64/libdbtasks12.so
rm -f lib64/libdbtasks12.so.1
rm -f lib64/libdbtasks12_r.so
rm -f lib64/libdbtasks12_r.so.1
rm -f lib64/libdbtool12_r.so
rm -f lib64/libdbtool12_r.so.1
rm -f lib64/libdbxgtk12_r.so
rm -f lib64/libdbxgtk12_r.so.1
rm -f lib64/libjsyblib610_r.so
rm -f lib64/libjsyblib610_r.so.1
rm -f lib64/libmlcrsa12_r.so
rm -f lib64/libmlcrsa12_r.so.1
rm -f lib64/libmlcrsafips12_r.so
rm -f lib64/libmlcrsafips12_r.so.1
rm -f lib64/libmlczlib12_r.so
rm -f lib64/libmlczlib12_r.so.1
rm -f lib64/libmlhttp12_r.so
rm -f lib64/libmlhttp12_r.so.1
rm -f lib64/libmljava12_r.so
rm -f lib64/libmljava12_r.so.1
rm -f lib64/libmljodbc12.so
rm -f lib64/libmljodbc12.so.1
rm -f lib64/libmljstrm12_r.so
rm -f lib64/libmljstrm12_r.so.1
rm -f lib64/libmlodbc12_r.so
rm -f lib64/libmlodbc12_r.so.1
rm -f lib64/libmlreplaylib_r.so
rm -f lib64/libmlreplaylib_r.so.1
rm -f lib64/libmlrsa_tls12_r.so
rm -f lib64/libmlrsa_tls12_r.so.1
rm -f lib64/libmlrsa_tls_fips12_r.so
rm -f lib64/libmlrsa_tls_fips12_r.so.1
rm -f lib64/libmlsock12_r.so
rm -f lib64/libmlsock12_r.so.1
rm -f lib64/libmlsql12_r.so
rm -f lib64/libmlsql12_r.so.1
rm -f lib64/libodbcinst.so
rm -f lib64/libodbcinst.so.1
rm -f lib64/librsoesupp12_r.so
rm -f lib64/librsoesupp12_r.so.1
rm -f lib64/libssl.so
rm -f lib64/libssl.so.1.0.0
rm -f lib64/libsybbr.so
rm -f lib64/libsybbr.so.1
rm -f lib64/php-5.1.1_sqlanywhere.so
rm -f lib64/php-5.1.1_sqlanywhere.so.1
rm -f lib64/php-5.1.1_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.1_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.1_sqlanywhere_r.so
rm -f lib64/php-5.1.1_sqlanywhere_r.so.1
rm -f lib64/php-5.1.2_sqlanywhere.so
rm -f lib64/php-5.1.2_sqlanywhere.so.1
rm -f lib64/php-5.1.2_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.2_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.2_sqlanywhere_r.so
rm -f lib64/php-5.1.2_sqlanywhere_r.so.1
rm -f lib64/php-5.1.3_sqlanywhere.so
rm -f lib64/php-5.1.3_sqlanywhere.so.1
rm -f lib64/php-5.1.3_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.3_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.3_sqlanywhere_r.so
rm -f lib64/php-5.1.3_sqlanywhere_r.so.1
rm -f lib64/php-5.1.4_sqlanywhere.so
rm -f lib64/php-5.1.4_sqlanywhere.so.1
rm -f lib64/php-5.1.4_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.4_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.4_sqlanywhere_r.so
rm -f lib64/php-5.1.4_sqlanywhere_r.so.1
rm -f lib64/php-5.1.5_sqlanywhere.so
rm -f lib64/php-5.1.5_sqlanywhere.so.1
rm -f lib64/php-5.1.5_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.5_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.5_sqlanywhere_r.so
rm -f lib64/php-5.1.5_sqlanywhere_r.so.1
rm -f lib64/php-5.1.6_sqlanywhere.so
rm -f lib64/php-5.1.6_sqlanywhere.so.1
rm -f lib64/php-5.1.6_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.1.6_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.1.6_sqlanywhere_r.so
rm -f lib64/php-5.1.6_sqlanywhere_r.so.1
rm -f lib64/php-5.2.0_sqlanywhere.so
rm -f lib64/php-5.2.0_sqlanywhere.so.1
rm -f lib64/php-5.2.0_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.0_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.0_sqlanywhere_r.so
rm -f lib64/php-5.2.0_sqlanywhere_r.so.1
rm -f lib64/php-5.2.10_sqlanywhere.so
rm -f lib64/php-5.2.10_sqlanywhere.so.1
rm -f lib64/php-5.2.10_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.10_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.10_sqlanywhere_r.so
rm -f lib64/php-5.2.10_sqlanywhere_r.so.1
rm -f lib64/php-5.2.11_sqlanywhere.so
rm -f lib64/php-5.2.11_sqlanywhere.so.1
rm -f lib64/php-5.2.11_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.11_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.11_sqlanywhere_r.so
rm -f lib64/php-5.2.11_sqlanywhere_r.so.1
rm -f lib64/php-5.2.12_sqlanywhere.so
rm -f lib64/php-5.2.12_sqlanywhere.so.1
rm -f lib64/php-5.2.12_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.12_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.12_sqlanywhere_r.so
rm -f lib64/php-5.2.12_sqlanywhere_r.so.1
rm -f lib64/php-5.2.13_sqlanywhere.so
rm -f lib64/php-5.2.13_sqlanywhere.so.1
rm -f lib64/php-5.2.13_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.13_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.13_sqlanywhere_r.so
rm -f lib64/php-5.2.13_sqlanywhere_r.so.1
rm -f lib64/php-5.2.14_sqlanywhere.so
rm -f lib64/php-5.2.14_sqlanywhere.so.1
rm -f lib64/php-5.2.14_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.14_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.14_sqlanywhere_r.so
rm -f lib64/php-5.2.14_sqlanywhere_r.so.1
rm -f lib64/php-5.2.15_sqlanywhere.so
rm -f lib64/php-5.2.15_sqlanywhere.so.1
rm -f lib64/php-5.2.15_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.15_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.15_sqlanywhere_r.so
rm -f lib64/php-5.2.15_sqlanywhere_r.so.1
rm -f lib64/php-5.2.16_sqlanywhere.so
rm -f lib64/php-5.2.16_sqlanywhere.so.1
rm -f lib64/php-5.2.16_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.16_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.16_sqlanywhere_r.so
rm -f lib64/php-5.2.16_sqlanywhere_r.so.1
rm -f lib64/php-5.2.17_sqlanywhere.so
rm -f lib64/php-5.2.17_sqlanywhere.so.1
rm -f lib64/php-5.2.17_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.17_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.17_sqlanywhere_r.so
rm -f lib64/php-5.2.17_sqlanywhere_r.so.1
rm -f lib64/php-5.2.1_sqlanywhere.so
rm -f lib64/php-5.2.1_sqlanywhere.so.1
rm -f lib64/php-5.2.1_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.1_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.1_sqlanywhere_r.so
rm -f lib64/php-5.2.1_sqlanywhere_r.so.1
rm -f lib64/php-5.2.2_sqlanywhere.so
rm -f lib64/php-5.2.2_sqlanywhere.so.1
rm -f lib64/php-5.2.2_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.2_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.2_sqlanywhere_r.so
rm -f lib64/php-5.2.2_sqlanywhere_r.so.1
rm -f lib64/php-5.2.3_sqlanywhere.so
rm -f lib64/php-5.2.3_sqlanywhere.so.1
rm -f lib64/php-5.2.3_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.3_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.3_sqlanywhere_r.so
rm -f lib64/php-5.2.3_sqlanywhere_r.so.1
rm -f lib64/php-5.2.4_sqlanywhere.so
rm -f lib64/php-5.2.4_sqlanywhere.so.1
rm -f lib64/php-5.2.4_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.4_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.4_sqlanywhere_r.so
rm -f lib64/php-5.2.4_sqlanywhere_r.so.1
rm -f lib64/php-5.2.5_sqlanywhere.so
rm -f lib64/php-5.2.5_sqlanywhere.so.1
rm -f lib64/php-5.2.5_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.5_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.5_sqlanywhere_r.so
rm -f lib64/php-5.2.5_sqlanywhere_r.so.1
rm -f lib64/php-5.2.6_sqlanywhere.so
rm -f lib64/php-5.2.6_sqlanywhere.so.1
rm -f lib64/php-5.2.6_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.6_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.6_sqlanywhere_r.so
rm -f lib64/php-5.2.6_sqlanywhere_r.so.1
rm -f lib64/php-5.2.8_sqlanywhere.so
rm -f lib64/php-5.2.8_sqlanywhere.so.1
rm -f lib64/php-5.2.8_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.8_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.8_sqlanywhere_r.so
rm -f lib64/php-5.2.8_sqlanywhere_r.so.1
rm -f lib64/php-5.2.9_sqlanywhere.so
rm -f lib64/php-5.2.9_sqlanywhere.so.1
rm -f lib64/php-5.2.9_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.2.9_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.2.9_sqlanywhere_r.so
rm -f lib64/php-5.2.9_sqlanywhere_r.so.1
rm -f lib64/php-5.3.0_sqlanywhere.so
rm -f lib64/php-5.3.0_sqlanywhere.so.1
rm -f lib64/php-5.3.0_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.0_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.0_sqlanywhere_r.so
rm -f lib64/php-5.3.0_sqlanywhere_r.so.1
rm -f lib64/php-5.3.10_sqlanywhere.so
rm -f lib64/php-5.3.10_sqlanywhere.so.1
rm -f lib64/php-5.3.10_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.10_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.10_sqlanywhere_r.so
rm -f lib64/php-5.3.10_sqlanywhere_r.so.1
rm -f lib64/php-5.3.11_sqlanywhere.so
rm -f lib64/php-5.3.11_sqlanywhere.so.1
rm -f lib64/php-5.3.11_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.11_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.11_sqlanywhere_r.so
rm -f lib64/php-5.3.11_sqlanywhere_r.so.1
rm -f lib64/php-5.3.12_sqlanywhere.so
rm -f lib64/php-5.3.12_sqlanywhere.so.1
rm -f lib64/php-5.3.12_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.12_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.12_sqlanywhere_r.so
rm -f lib64/php-5.3.12_sqlanywhere_r.so.1
rm -f lib64/php-5.3.13_sqlanywhere.so
rm -f lib64/php-5.3.13_sqlanywhere.so.1
rm -f lib64/php-5.3.13_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.13_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.13_sqlanywhere_r.so
rm -f lib64/php-5.3.13_sqlanywhere_r.so.1
rm -f lib64/php-5.3.14_sqlanywhere.so
rm -f lib64/php-5.3.14_sqlanywhere.so.1
rm -f lib64/php-5.3.14_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.14_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.14_sqlanywhere_r.so
rm -f lib64/php-5.3.14_sqlanywhere_r.so.1
rm -f lib64/php-5.3.15_sqlanywhere.so
rm -f lib64/php-5.3.15_sqlanywhere.so.1
rm -f lib64/php-5.3.15_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.15_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.15_sqlanywhere_r.so
rm -f lib64/php-5.3.15_sqlanywhere_r.so.1
rm -f lib64/php-5.3.16_sqlanywhere.so
rm -f lib64/php-5.3.16_sqlanywhere.so.1
rm -f lib64/php-5.3.16_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.16_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.16_sqlanywhere_r.so
rm -f lib64/php-5.3.16_sqlanywhere_r.so.1
rm -f lib64/php-5.3.17_sqlanywhere.so
rm -f lib64/php-5.3.17_sqlanywhere.so.1
rm -f lib64/php-5.3.17_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.17_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.17_sqlanywhere_r.so
rm -f lib64/php-5.3.17_sqlanywhere_r.so.1
rm -f lib64/php-5.3.18_sqlanywhere.so
rm -f lib64/php-5.3.18_sqlanywhere.so.1
rm -f lib64/php-5.3.18_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.18_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.18_sqlanywhere_r.so
rm -f lib64/php-5.3.18_sqlanywhere_r.so.1
rm -f lib64/php-5.3.19_sqlanywhere.so
rm -f lib64/php-5.3.19_sqlanywhere.so.1
rm -f lib64/php-5.3.19_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.19_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.19_sqlanywhere_r.so
rm -f lib64/php-5.3.19_sqlanywhere_r.so.1
rm -f lib64/php-5.3.1_sqlanywhere.so
rm -f lib64/php-5.3.1_sqlanywhere.so.1
rm -f lib64/php-5.3.1_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.1_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.1_sqlanywhere_r.so
rm -f lib64/php-5.3.1_sqlanywhere_r.so.1
rm -f lib64/php-5.3.20_sqlanywhere.so
rm -f lib64/php-5.3.20_sqlanywhere.so.1
rm -f lib64/php-5.3.20_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.20_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.20_sqlanywhere_r.so
rm -f lib64/php-5.3.20_sqlanywhere_r.so.1
rm -f lib64/php-5.3.21_sqlanywhere.so
rm -f lib64/php-5.3.21_sqlanywhere.so.1
rm -f lib64/php-5.3.21_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.21_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.21_sqlanywhere_r.so
rm -f lib64/php-5.3.21_sqlanywhere_r.so.1
rm -f lib64/php-5.3.22_sqlanywhere.so
rm -f lib64/php-5.3.22_sqlanywhere.so.1
rm -f lib64/php-5.3.22_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.22_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.22_sqlanywhere_r.so
rm -f lib64/php-5.3.22_sqlanywhere_r.so.1
rm -f lib64/php-5.3.23_sqlanywhere.so
rm -f lib64/php-5.3.23_sqlanywhere.so.1
rm -f lib64/php-5.3.23_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.23_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.23_sqlanywhere_r.so
rm -f lib64/php-5.3.23_sqlanywhere_r.so.1
rm -f lib64/php-5.3.24_sqlanywhere.so
rm -f lib64/php-5.3.24_sqlanywhere.so.1
rm -f lib64/php-5.3.24_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.24_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.24_sqlanywhere_r.so
rm -f lib64/php-5.3.24_sqlanywhere_r.so.1
rm -f lib64/php-5.3.25_sqlanywhere.so
rm -f lib64/php-5.3.25_sqlanywhere.so.1
rm -f lib64/php-5.3.25_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.25_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.25_sqlanywhere_r.so
rm -f lib64/php-5.3.25_sqlanywhere_r.so.1
rm -f lib64/php-5.3.26_sqlanywhere.so
rm -f lib64/php-5.3.26_sqlanywhere.so.1
rm -f lib64/php-5.3.26_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.26_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.26_sqlanywhere_r.so
rm -f lib64/php-5.3.26_sqlanywhere_r.so.1
rm -f lib64/php-5.3.2_sqlanywhere.so
rm -f lib64/php-5.3.2_sqlanywhere.so.1
rm -f lib64/php-5.3.2_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.2_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.2_sqlanywhere_r.so
rm -f lib64/php-5.3.2_sqlanywhere_r.so.1
rm -f lib64/php-5.3.3_sqlanywhere.so
rm -f lib64/php-5.3.3_sqlanywhere.so.1
rm -f lib64/php-5.3.3_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.3_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.3_sqlanywhere_r.so
rm -f lib64/php-5.3.3_sqlanywhere_r.so.1
rm -f lib64/php-5.3.4_sqlanywhere.so
rm -f lib64/php-5.3.4_sqlanywhere.so.1
rm -f lib64/php-5.3.4_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.4_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.4_sqlanywhere_r.so
rm -f lib64/php-5.3.4_sqlanywhere_r.so.1
rm -f lib64/php-5.3.5_sqlanywhere.so
rm -f lib64/php-5.3.5_sqlanywhere.so.1
rm -f lib64/php-5.3.5_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.5_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.5_sqlanywhere_r.so
rm -f lib64/php-5.3.5_sqlanywhere_r.so.1
rm -f lib64/php-5.3.6_sqlanywhere.so
rm -f lib64/php-5.3.6_sqlanywhere.so.1
rm -f lib64/php-5.3.6_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.6_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.6_sqlanywhere_r.so
rm -f lib64/php-5.3.6_sqlanywhere_r.so.1
rm -f lib64/php-5.3.7_sqlanywhere.so
rm -f lib64/php-5.3.7_sqlanywhere.so.1
rm -f lib64/php-5.3.7_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.7_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.7_sqlanywhere_r.so
rm -f lib64/php-5.3.7_sqlanywhere_r.so.1
rm -f lib64/php-5.3.8_sqlanywhere.so
rm -f lib64/php-5.3.8_sqlanywhere.so.1
rm -f lib64/php-5.3.8_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.8_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.8_sqlanywhere_r.so
rm -f lib64/php-5.3.8_sqlanywhere_r.so.1
rm -f lib64/php-5.3.9_sqlanywhere.so
rm -f lib64/php-5.3.9_sqlanywhere.so.1
rm -f lib64/php-5.3.9_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.3.9_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.3.9_sqlanywhere_r.so
rm -f lib64/php-5.3.9_sqlanywhere_r.so.1
rm -f lib64/php-5.4.0_sqlanywhere.so
rm -f lib64/php-5.4.0_sqlanywhere.so.1
rm -f lib64/php-5.4.0_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.0_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.0_sqlanywhere_r.so
rm -f lib64/php-5.4.0_sqlanywhere_r.so.1
rm -f lib64/php-5.4.10_sqlanywhere.so
rm -f lib64/php-5.4.10_sqlanywhere.so.1
rm -f lib64/php-5.4.10_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.10_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.10_sqlanywhere_r.so
rm -f lib64/php-5.4.10_sqlanywhere_r.so.1
rm -f lib64/php-5.4.11_sqlanywhere.so
rm -f lib64/php-5.4.11_sqlanywhere.so.1
rm -f lib64/php-5.4.11_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.11_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.11_sqlanywhere_r.so
rm -f lib64/php-5.4.11_sqlanywhere_r.so.1
rm -f lib64/php-5.4.12_sqlanywhere.so
rm -f lib64/php-5.4.12_sqlanywhere.so.1
rm -f lib64/php-5.4.12_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.12_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.12_sqlanywhere_r.so
rm -f lib64/php-5.4.12_sqlanywhere_r.so.1
rm -f lib64/php-5.4.13_sqlanywhere.so
rm -f lib64/php-5.4.13_sqlanywhere.so.1
rm -f lib64/php-5.4.13_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.13_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.13_sqlanywhere_r.so
rm -f lib64/php-5.4.13_sqlanywhere_r.so.1
rm -f lib64/php-5.4.14_sqlanywhere.so
rm -f lib64/php-5.4.14_sqlanywhere.so.1
rm -f lib64/php-5.4.14_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.14_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.14_sqlanywhere_r.so
rm -f lib64/php-5.4.14_sqlanywhere_r.so.1
rm -f lib64/php-5.4.15_sqlanywhere.so
rm -f lib64/php-5.4.15_sqlanywhere.so.1
rm -f lib64/php-5.4.15_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.15_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.15_sqlanywhere_r.so
rm -f lib64/php-5.4.15_sqlanywhere_r.so.1
rm -f lib64/php-5.4.16_sqlanywhere.so
rm -f lib64/php-5.4.16_sqlanywhere.so.1
rm -f lib64/php-5.4.16_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.16_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.16_sqlanywhere_r.so
rm -f lib64/php-5.4.16_sqlanywhere_r.so.1
rm -f lib64/php-5.4.1_sqlanywhere.so
rm -f lib64/php-5.4.1_sqlanywhere.so.1
rm -f lib64/php-5.4.1_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.1_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.1_sqlanywhere_r.so
rm -f lib64/php-5.4.1_sqlanywhere_r.so.1
rm -f lib64/php-5.4.2_sqlanywhere.so
rm -f lib64/php-5.4.2_sqlanywhere.so.1
rm -f lib64/php-5.4.2_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.2_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.2_sqlanywhere_r.so
rm -f lib64/php-5.4.2_sqlanywhere_r.so.1
rm -f lib64/php-5.4.3_sqlanywhere.so
rm -f lib64/php-5.4.3_sqlanywhere.so.1
rm -f lib64/php-5.4.3_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.3_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.3_sqlanywhere_r.so
rm -f lib64/php-5.4.3_sqlanywhere_r.so.1
rm -f lib64/php-5.4.4_sqlanywhere.so
rm -f lib64/php-5.4.4_sqlanywhere.so.1
rm -f lib64/php-5.4.4_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.4_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.4_sqlanywhere_r.so
rm -f lib64/php-5.4.4_sqlanywhere_r.so.1
rm -f lib64/php-5.4.5_sqlanywhere.so
rm -f lib64/php-5.4.5_sqlanywhere.so.1
rm -f lib64/php-5.4.5_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.5_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.5_sqlanywhere_r.so
rm -f lib64/php-5.4.5_sqlanywhere_r.so.1
rm -f lib64/php-5.4.6_sqlanywhere.so
rm -f lib64/php-5.4.6_sqlanywhere.so.1
rm -f lib64/php-5.4.6_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.6_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.6_sqlanywhere_r.so
rm -f lib64/php-5.4.6_sqlanywhere_r.so.1
rm -f lib64/php-5.4.7_sqlanywhere.so
rm -f lib64/php-5.4.7_sqlanywhere.so.1
rm -f lib64/php-5.4.7_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.7_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.7_sqlanywhere_r.so
rm -f lib64/php-5.4.7_sqlanywhere_r.so.1
rm -f lib64/php-5.4.8_sqlanywhere.so
rm -f lib64/php-5.4.8_sqlanywhere.so.1
rm -f lib64/php-5.4.8_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.8_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.8_sqlanywhere_r.so
rm -f lib64/php-5.4.8_sqlanywhere_r.so.1
rm -f lib64/php-5.4.9_sqlanywhere.so
rm -f lib64/php-5.4.9_sqlanywhere.so.1
rm -f lib64/php-5.4.9_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.4.9_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.4.9_sqlanywhere_r.so
rm -f lib64/php-5.4.9_sqlanywhere_r.so.1
rm -f lib64/php-5.5.0_sqlanywhere.so
rm -f lib64/php-5.5.0_sqlanywhere.so.1
rm -f lib64/php-5.5.0_sqlanywhere_extenv12_r.so
rm -f lib64/php-5.5.0_sqlanywhere_extenv12_r.so.1
rm -f lib64/php-5.5.0_sqlanywhere_r.so
rm -f lib64/php-5.5.0_sqlanywhere_r.so.1
rm -f mobilink/mlarbiter.control
rm -f mobilink/setup/odbc.ini.sample
rm -f mobilink/setup/syncase.sql
rm -f mobilink/setup/syncdb2.sql
rm -f mobilink/setup/synciq.sql
rm -f mobilink/setup/syncmys.sql
rm -f mobilink/setup/syncora.sql
rm -f mobilink/setup/syncsa.sql
rm -f mobilink/upgrade/10.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/10.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/10.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/10.0.x/upgrade_sa.sql
rm -f mobilink/upgrade/11.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/11.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/11.0.x/upgrade_mys.sql
rm -f mobilink/upgrade/11.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/11.0.x/upgrade_sa.sql
rm -f mobilink/upgrade/12.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/12.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/12.0.0/upgrade_mys.sql
rm -f mobilink/upgrade/12.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/12.0.0/upgrade_sa.sql
rm -f mobilink/upgrade/7.0.x/readme.txt
rm -f mobilink/upgrade/7.0.x/upgrade_asa.sql
rm -f mobilink/upgrade/7.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/7.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/7.0.x/upgrade_db2tolong.sql
rm -f mobilink/upgrade/7.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.0/readme.txt
rm -f mobilink/upgrade/8.0.0/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.0/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.1/readme.txt
rm -f mobilink/upgrade/8.0.1/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.1/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.1/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.1/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.1/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.x/readme.txt
rm -f mobilink/upgrade/8.0.x/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.x/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.0/readme.txt
rm -f mobilink/upgrade/9.0.0/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.0/upgrade_db2tolong.sql
rm -f mobilink/upgrade/9.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.1/readme.txt
rm -f mobilink/upgrade/9.0.1/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.1/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.1/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.1/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.2/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.2/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.2/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.2/upgrade_ora.sql
rm -f rdme*.ebf
rm -f rdme_1201_core_ebf_4127.html
rm -f rdme_1201_core_ebf_4127.txt
rm -f rdme_1201_ebf_4127.html
rm -f rdme_1201_ebf_4127.txt
rm -f readme
rm -f readme_de.txt
rm -f readme_en.txt
rm -f readme_fr.txt
rm -f readme_ja.txt
rm -f readme_zh.txt
rm -f relayserver/apache/bin32/mod_rs_ap_admin.so
rm -f relayserver/apache/bin32/mod_rs_ap_admin.so.1
rm -f relayserver/apache/bin32/mod_rs_ap_client.so
rm -f relayserver/apache/bin32/mod_rs_ap_client.so.1
rm -f relayserver/apache/bin32/mod_rs_ap_monitor.so
rm -f relayserver/apache/bin32/mod_rs_ap_monitor.so.1
rm -f relayserver/apache/bin32/mod_rs_ap_server.so
rm -f relayserver/apache/bin32/mod_rs_ap_server.so.1
rm -f relayserver/apache/bin32/rs.config.sample
rm -f relayserver/apache/bin32/rshost
rm -f relayserver/apache/bin32s/mod_rs_ap_admin.so
rm -f relayserver/apache/bin32s/mod_rs_ap_admin.so.1
rm -f relayserver/apache/bin32s/mod_rs_ap_client.so
rm -f relayserver/apache/bin32s/mod_rs_ap_client.so.1
rm -f relayserver/apache/bin32s/mod_rs_ap_monitor.so
rm -f relayserver/apache/bin32s/mod_rs_ap_monitor.so.1
rm -f relayserver/apache/bin32s/mod_rs_ap_server.so
rm -f relayserver/apache/bin32s/mod_rs_ap_server.so.1
rm -f relayserver/apache/bin32s/rs.config.sample
rm -f relayserver/apache/bin32s/rshost
rm -f relayserver/apache/bin64/mod_rs_ap_admin.so
rm -f relayserver/apache/bin64/mod_rs_ap_admin.so.1
rm -f relayserver/apache/bin64/mod_rs_ap_client.so
rm -f relayserver/apache/bin64/mod_rs_ap_client.so.1
rm -f relayserver/apache/bin64/mod_rs_ap_monitor.so
rm -f relayserver/apache/bin64/mod_rs_ap_monitor.so.1
rm -f relayserver/apache/bin64/mod_rs_ap_server.so
rm -f relayserver/apache/bin64/mod_rs_ap_server.so.1
rm -f relayserver/apache/bin64/rs.config.sample
rm -f relayserver/apache/bin64/rshost
rm -f relayserver/apache/bin64s/mod_rs_ap_admin.so
rm -f relayserver/apache/bin64s/mod_rs_ap_admin.so.1
rm -f relayserver/apache/bin64s/mod_rs_ap_client.so
rm -f relayserver/apache/bin64s/mod_rs_ap_client.so.1
rm -f relayserver/apache/bin64s/mod_rs_ap_monitor.so
rm -f relayserver/apache/bin64s/mod_rs_ap_monitor.so.1
rm -f relayserver/apache/bin64s/mod_rs_ap_server.so
rm -f relayserver/apache/bin64s/mod_rs_ap_server.so.1
rm -f relayserver/apache/bin64s/rs.config.sample
rm -f relayserver/apache/bin64s/rshost
rm -f relayserver/apache/quicksetup_apache/SimpleTestApp.htm
rm -f relayserver/apache/quicksetup_apache/__ap-setup__.sh
rm -f relayserver/apache/quicksetup_apache/__funcs__.sh
rm -f relayserver/apache/quicksetup_apache/__rs-test-setup__.sh
rm -f relayserver/apache/quicksetup_apache/add_envvars_path.pl
rm -f relayserver/apache/quicksetup_apache/add_rs_config.pl
rm -f relayserver/apache/quicksetup_apache/ap-setup.sh
rm -f relayserver/apache/quicksetup_apache/quick-ref.template.htm
rm -f relayserver/apache/quicksetup_apache/remove_rs_config.pl
rm -f relayserver/apache/quicksetup_apache/rs-test-setup.sh
rm -f relayserver/apache/quicksetup_apache/tee.pl
rm -f res/DBConsole.png
rm -f res/InteractiveSQL.png
rm -f res/MobiLinkMonitor.png
rm -f res/SAMonitor16.png
rm -f res/SQLAnywhere.png
rm -f res/SQLAnywhereServer.png
rm -f res/SybaseCentral.png
rm -f res/dblgde12_iso_1.res
rm -f res/dblgde12_utf8.res
rm -f res/dblgen12.res
rm -f res/dblgfr12_iso_1.res
rm -f res/dblgfr12_utf8.res
rm -f res/dblgja12_eucjis.res
rm -f res/dblgja12_sjis.res
rm -f res/dblgja12_utf8.res
rm -f res/dblgzh12_cp936.res
rm -f res/dblgzh12_eucgb.res
rm -f res/dblgzh12_utf8.res
rm -f res/dbusde_iso_1.res
rm -f res/dbusde_utf8.res
rm -f res/dbusen.res
rm -f res/dbusja_eucjis.res
rm -f res/dbusja_sjis.res
rm -f res/dbusja_utf8.res
rm -f res/dbuszh_cp936.res
rm -f res/dbuszh_eucgb.res
rm -f res/dbuszh_utf8.res
rm -f res/sqlany.cvf
rm -f sadoc_readme_de.txt
rm -f sadoc_readme_en.txt
rm -f sadoc_readme_fr.txt
rm -f sadoc_readme_ja.txt
rm -f sadoc_readme_zh.txt
rm -f samonitor.db
rm -f samonitor.log
rm -f samples/mobilink/contact/build.sh
rm -f samples/mobilink/contact/build_consol.sql
rm -f samples/mobilink/contact/build_remote.sql
rm -f samples/mobilink/contact/clean.sh
rm -f samples/mobilink/contact/customize.sql
rm -f samples/mobilink/contact/mlmaint.sql
rm -f samples/mobilink/contact/readme.txt
rm -f samples/mobilink/contact/readme_ja.txt
rm -f samples/mobilink/contact/report.sh
rm -f samples/mobilink/contact/report.sql
rm -f samples/mobilink/contact/step1.sh
rm -f samples/mobilink/contact/step2.sh
rm -f samples/mobilink/contact/step3.sh
rm -f samples/mobilink/custdb/project.mlp
rm -f samples/mobilink/globalautoincrement/build.sh
rm -f samples/mobilink/globalautoincrement/build_consol.sql
rm -f samples/mobilink/globalautoincrement/build_remote.sql
rm -f samples/mobilink/globalautoincrement/clean.sh
rm -f samples/mobilink/globalautoincrement/consol_inserts.sql
rm -f samples/mobilink/globalautoincrement/readme.txt
rm -f samples/mobilink/globalautoincrement/readme_ja.txt
rm -f samples/mobilink/globalautoincrement/remote_1_inserts.sql
rm -f samples/mobilink/globalautoincrement/remote_2_inserts.sql
rm -f samples/mobilink/globalautoincrement/report.sh
rm -f samples/mobilink/globalautoincrement/report.sql
rm -f samples/mobilink/globalautoincrement/step1.sh
rm -f samples/mobilink/globalautoincrement/step2.sh
rm -f samples/mobilink/globalautoincrement/step3.sh
rm -f samples/mobilink/java_authentication/CustEmpScripts.java
rm -f samples/mobilink/java_authentication/add_data_consol.sql
rm -f samples/mobilink/java_authentication/build.sh
rm -f samples/mobilink/java_authentication/build_consol.sql
rm -f samples/mobilink/java_authentication/build_remote.sql
rm -f samples/mobilink/java_authentication/clean.sh
rm -f samples/mobilink/java_authentication/readme.txt
rm -f samples/mobilink/java_authentication/readme_ja.txt
rm -f samples/mobilink/java_authentication/report.sh
rm -f samples/mobilink/java_authentication/report_consol.sql
rm -f samples/mobilink/java_authentication/report_remote.sql
rm -f samples/mobilink/java_authentication/step1.sh
rm -f samples/mobilink/java_authentication/step2.sh
rm -f samples/mobilink/java_authentication/step3.sh
rm -f samples/mobilink/mlreplay/build.sh
rm -f samples/mobilink/mlreplay/clean.sh
rm -f samples/mobilink/mlreplay/cons.sql
rm -f samples/mobilink/mlreplay/readme.txt
rm -f samples/mobilink/mlreplay/readme_ja.txt
rm -f samples/mobilink/mlreplay/remote.sql
rm -f samples/mobilink/mlreplay/report.sh
rm -f samples/mobilink/mlreplay/step1.sh
rm -f samples/mobilink/mlreplay/step2.sh
rm -f samples/mobilink/mlreplay/step3.sh
rm -f samples/mobilink/mlreplay/step4.sh
rm -f samples/mobilink/mlreplay/step5.sh
rm -f samples/mobilink/mlreplay/step6.sh
rm -f samples/mobilink/mlreplay/step7.sh
rm -f samples/mobilink/mlreplay/step8.sh
rm -f samples/mobilink/partitioning/build.sh
rm -f samples/mobilink/partitioning/build_consol.sql
rm -f samples/mobilink/partitioning/build_remote.sql
rm -f samples/mobilink/partitioning/clean.sh
rm -f samples/mobilink/partitioning/consol_inserts.sql
rm -f samples/mobilink/partitioning/readme.txt
rm -f samples/mobilink/partitioning/readme_ja.txt
rm -f samples/mobilink/partitioning/remote_1_inserts.sql
rm -f samples/mobilink/partitioning/remote_2_inserts.sql
rm -f samples/mobilink/partitioning/report.sh
rm -f samples/mobilink/partitioning/report.sql
rm -f samples/mobilink/partitioning/step1.sh
rm -f samples/mobilink/partitioning/step2.sh
rm -f samples/mobilink/partitioning/step3.sh
rm -f samples/qanywhere/server/qanyserv.db
rm -f samples/qanywhere/server/readme.txt
rm -f samples/sample_config32.sh
rm -f samples/sample_config64.sh
rm -f samples/sample_env32.sh
rm -f samples/sample_env64.sh
rm -f samples/sqlanywhere/c/build.sh
rm -f samples/sqlanywhere/c/clean.sh
rm -f samples/sqlanywhere/c/cur.sqc
rm -f samples/sqlanywhere/c/dcur.sqc
rm -f samples/sqlanywhere/c/example.h
rm -f samples/sqlanywhere/c/mainch.c
rm -f samples/sqlanywhere/c/odbc.c
rm -f samples/sqlanywhere/dbtools/build.sh
rm -f samples/sqlanywhere/dbtools/clean.sh
rm -f samples/sqlanywhere/dbtools/main.cpp
rm -f samples/sqlanywhere/dbtools/readme.txt
rm -f samples/sqlanywhere/dbtools/readme_ja.txt
rm -f samples/sqlanywhere/dbtools/run.sh
rm -f samples/sqlanywhere/diskfull/build.sh
rm -f samples/sqlanywhere/diskfull/clean.sh
rm -f samples/sqlanywhere/diskfull/diskfull.cpp
rm -f samples/sqlanywhere/diskfull/readme.txt
rm -f samples/sqlanywhere/diskfull/readme_ja.txt
rm -f samples/sqlanywhere/diskfull/show_exports.sh
rm -f samples/sqlanywhere/externalenvironments/externc/datatype.sql
rm -f samples/sqlanywhere/externalenvironments/externc/resultset.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/resultset.sql
rm -f samples/sqlanywhere/externalenvironments/externc/serverside.sql
rm -f samples/sqlanywhere/externalenvironments/externc/serversideesql.sqc
rm -f samples/sqlanywhere/externalenvironments/externc/serversideodbc.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/testsrc.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/testsrc.h
rm -f samples/sqlanywhere/externalenvironments/perl/datatype.pl
rm -f samples/sqlanywhere/externalenvironments/perl/datatype.sql
rm -f samples/sqlanywhere/externalenvironments/perl/serverside.pl
rm -f samples/sqlanywhere/externalenvironments/perl/serverside.sql
rm -f samples/sqlanywhere/externalenvironments/php/datatype.php
rm -f samples/sqlanywhere/externalenvironments/php/datatype.sql
rm -f samples/sqlanywhere/externalenvironments/php/http.sql
rm -f samples/sqlanywhere/externalenvironments/php/index.php
rm -f samples/sqlanywhere/externalenvironments/php/phpinfo.php
rm -f samples/sqlanywhere/externalenvironments/php/sa_session.php
rm -f samples/sqlanywhere/externalenvironments/php/serverside.php
rm -f samples/sqlanywhere/externalenvironments/php/serverside.sql
rm -f samples/sqlanywhere/externalenvironments/php/session.php
rm -f samples/sqlanywhere/externallibrariesfulltext/build.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/clean.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample.cpp
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample_tests.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/readme.txt
rm -f samples/sqlanywhere/externallibrariesfulltext/readme_ja.txt
rm -f samples/sqlanywhere/externallibrariesfulltext/show_exports.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample.cpp
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample_tests.sql
rm -f samples/sqlanywhere/externalprocedures/build.sh
rm -f samples/sqlanywhere/externalprocedures/clean.sh
rm -f samples/sqlanywhere/externalprocedures/extproc.cpp
rm -f samples/sqlanywhere/externalprocedures/extproc.sql
rm -f samples/sqlanywhere/externalprocedures/readme.txt
rm -f samples/sqlanywhere/externalprocedures/readme_ja.txt
rm -f samples/sqlanywhere/externalprocedures/show_exports.sh
rm -f samples/sqlanywhere/externalprocedures/tests.sql
rm -f samples/sqlanywhere/http/cookie.sql
rm -f samples/sqlanywhere/http/gallery.sql
rm -f samples/sqlanywhere/http/globalweather.wsdl
rm -f samples/sqlanywhere/http/gov.weather.wsdl
rm -f samples/sqlanywhere/http/html_cal_test.sql
rm -f samples/sqlanywhere/http/html_calendar.sql
rm -f samples/sqlanywhere/http/html_select.sql
rm -f samples/sqlanywhere/http/image_readfile.sql
rm -f samples/sqlanywhere/http/json_sample.sql
rm -f samples/sqlanywhere/http/post_data.sql
rm -f samples/sqlanywhere/http/put_data.sql
rm -f samples/sqlanywhere/http/readme.txt
rm -f samples/sqlanywhere/http/session.sql
rm -f samples/sqlanywhere/http/show_request_info.sql
rm -f samples/sqlanywhere/http/show_table.sql
rm -f samples/sqlanywhere/http/soap.globalweather.sql
rm -f samples/sqlanywhere/http/soap.gov.weather.sql
rm -f samples/sqlanywhere/http/soapsession.sql
rm -f samples/sqlanywhere/http/test_request_db.sql
rm -f samples/sqlanywhere/javainvoice/Invoice.java
rm -f samples/sqlanywhere/javainvoice/build.sh
rm -f samples/sqlanywhere/javainvoice/clean.sh
rm -f samples/sqlanywhere/javainvoice/install.sql
rm -f samples/sqlanywhere/javainvoice/readme.txt
rm -f samples/sqlanywhere/javainvoice/readme_ja.txt
rm -f samples/sqlanywhere/javainvoice/remove.sql
rm -f samples/sqlanywhere/javainvoice/run.sh
rm -f samples/sqlanywhere/javainvoice/run.sql
rm -f samples/sqlanywhere/oemstring/build.sh
rm -f samples/sqlanywhere/oemstring/clean.sh
rm -f samples/sqlanywhere/oemstring/dboem.cpp
rm -f samples/sqlanywhere/oemstring/dboem.pl
rm -f samples/sqlanywhere/oemstring/readme.txt
rm -f samples/sqlanywhere/oemstring/readme_ja.txt
rm -f samples/sqlanywhere/performancefetch/build.sh
rm -f samples/sqlanywhere/performancefetch/clean.sh
rm -f samples/sqlanywhere/performancefetch/fetchtst.sqc
rm -f samples/sqlanywhere/performancefetch/odbcfet.c
rm -f samples/sqlanywhere/performancefetch/readme.txt
rm -f samples/sqlanywhere/performanceinsert/build.sh
rm -f samples/sqlanywhere/performanceinsert/clean.sh
rm -f samples/sqlanywhere/performanceinsert/instest.sqc
rm -f samples/sqlanywhere/performanceinsert/readme.txt
rm -f samples/sqlanywhere/performancetracetime/readme.txt
rm -f samples/sqlanywhere/performancetracetime/readme_ja.txt
rm -f samples/sqlanywhere/performancetracetime/tracetime.pl
rm -f samples/sqlanywhere/performancetransaction/build.sh
rm -f samples/sqlanywhere/performancetransaction/clean.sh
rm -f samples/sqlanywhere/performancetransaction/esqltran.sqc
rm -f samples/sqlanywhere/performancetransaction/odbctran.cpp
rm -f samples/sqlanywhere/performancetransaction/readme.txt
rm -f samples/sqlanywhere/performancetransaction/trantabs.sql
rm -f samples/sqlanywhere/performancetransaction/trantest.cpp
rm -f samples/sqlanywhere/performancetransaction/trantest.hpp
rm -f samples/sqlanywhere/performancetransaction/tranthrd.cpp
rm -f samples/sqlanywhere/performancetransaction/tranthrd.hpp
rm -f samples/sqlanywhere/performancetransaction/worklist.cpp
rm -f samples/sqlanywhere/sql/create_default_stoplist.sql
rm -f samples/sqlanywhere/sql/readme.txt
rm -f samples/sqlanywhere/sql/readme_ja.txt
rm -f samples/sqlanywhere/sql/sa_get_column_list.sql
rm -f samples/sqlanywhere/sql/simplify_geometry.sql
rm -f samples/sqlanywhere/sql/stopword_language.csv
rm -f samples/sqlanywhere/sql/stopword_table.csv
rm -f samples/sqlanywhere/sql/verify_password.sql
rm -f samples/start_mobilink_qanywhere_sample32.sh
rm -f samples/start_mobilink_qanywhere_sample64.sh
rm -f samples/ultralite/custdb/custdb.db
rm -f samples/ultralite/custdb/custdb.h
rm -f samples/ultralite/custdb/custdb.sqc
rm -f samples/ultralite/custdb/custdb.sql
rm -f samples/ultralite/custdb/custdb.udb
rm -f samples/ultralite/custdb/custdbcpp.cpp
rm -f samples/ultralite/custdb/grant.sql
rm -f samples/ultralite/custdb/linux/build.sh
rm -f samples/ultralite/custdb/linux/custio.c
rm -f samples/ultralite/custdb/linux/mobilink.sh
rm -f samples/ultralite/custdb/makedbs.sh
rm -f samples/ultralite/custdb/platform.h
rm -f samples/ultralite/custdb/readme.txt
rm -f samples/ultralite/starter/build.sh
rm -f samples/ultralite/starter/readme.txt
rm -f samples/ultralite/starter/ulsample.cpp
rm -f scripts/adata/ClothVisor.jpg
rm -f scripts/adata/CottonCap.jpg
rm -f scripts/adata/CottonShorts.jpg
rm -f scripts/adata/CrewNeck.jpg
rm -f scripts/adata/HoodedSweatshirt.jpg
rm -f scripts/adata/PlasticVisor.jpg
rm -f scripts/adata/TankTop.jpg
rm -f scripts/adata/V-Neck.jpg
rm -f scripts/adata/WoolCap.jpg
rm -f scripts/adata/ZippedSweatshirt.jpg
rm -f scripts/adata/contact.sql
rm -f scripts/adata/customer.sql
rm -f scripts/adata/dept.sql
rm -f scripts/adata/employee.sql
rm -f scripts/adata/fin_code.sql
rm -f scripts/adata/fin_data.sql
rm -f scripts/adata/marketinfo.sql
rm -f scripts/adata/product.sql
rm -f scripts/adata/sales_o.sql
rm -f scripts/adata/sales_oi.sql
rm -f scripts/adata/stcontacts.sql
rm -f scripts/adata/stshapes.sql
rm -f scripts/mkdemo.sql
rm -f scripts/optdeflt.sql
rm -f scripts/opttemp.sql
rm -f scripts/salespub.sql
rm -f scripts/st_geometry_config.tgz
rm -f scripts/unloadold.sql
rm -f sdk/c/sacapidll.c
rm -f sdk/c/ulcpp11.cpp
rm -f sdk/dbcapi/examples/build.sh
rm -f sdk/dbcapi/examples/connecting.cpp
rm -f sdk/dbcapi/examples/dbcapi_isql.cpp
rm -f sdk/dbcapi/examples/fetching_a_result_set.cpp
rm -f sdk/dbcapi/examples/fetching_multiple_from_sp.cpp
rm -f sdk/dbcapi/examples/preparing_statements.cpp
rm -f sdk/dbcapi/examples/send_retrieve_full_blob.cpp
rm -f sdk/dbcapi/examples/send_retrieve_part_blob.cpp
rm -f sdk/dbcapi/examples/stmt_exec.cpp
rm -f sdk/dbcapi/examples/stmt_reset.cpp
rm -f sdk/dbcapi/sacapi.h
rm -f sdk/dbcapi/sacapidll.c
rm -f sdk/dbcapi/sacapidll.h
rm -f sdk/include/dbrmt.h
rm -f sdk/include/dbtlvers.h
rm -f sdk/include/dbtools.h
rm -f sdk/include/dllapi.h
rm -f sdk/include/extfnapi.h
rm -f sdk/include/extfncmn.h
rm -f sdk/include/extpfapiv1.h
rm -f sdk/include/exttbapiv1.h
rm -f sdk/include/exttxtcmn.h
rm -f sdk/include/imlreplayuploadtable.hpp
rm -f sdk/include/imlreplayuploadtransaction.hpp
rm -f sdk/include/lictype.h
rm -f sdk/include/mlfiletransfer.h
rm -f sdk/include/mlreplayapicallbacks.hpp
rm -f sdk/include/mlreplaycallbacks.hpp
rm -f sdk/include/mlreplaycvector.hpp
rm -f sdk/include/odbc.h
rm -f sdk/include/poppk.h
rm -f sdk/include/pshpk1.h
rm -f sdk/include/pshpk2.h
rm -f sdk/include/pshpk4.h
rm -f sdk/include/sacapi.h
rm -f sdk/include/sacapidll.h
rm -f sdk/include/saodbc.h
rm -f sdk/include/sqlca.h
rm -f sdk/include/sqlcallback.h
rm -f sdk/include/sqlda.h
rm -f sdk/include/sqldef.h
rm -f sdk/include/sqlerr.h
rm -f sdk/include/sqlfuncs.h
rm -f sdk/include/sqlhosttype.h
rm -f sdk/include/sqlos.h
rm -f sdk/include/sqlstate.h
rm -f sdk/include/sqltype.h
rm -f sdk/include/sserror.h
rm -f sdk/include/ulcpp.h
rm -f sdk/include/uldef.h
rm -f sdk/include/ulglobal.h
rm -f sdk/include/uliface.h
rm -f sdk/include/ulprotos.h
rm -f sdk/include/ulsqlfuncs.h
rm -f sdk/include/unixodbc.h
rm -f sdk/perl/Changes
rm -f sdk/perl/MANIFEST
rm -f sdk/perl/Makefile.PL
rm -f sdk/perl/README
rm -f sdk/perl/README.NT
rm -f sdk/perl/SQLAnywhere.h
rm -f sdk/perl/SQLAnywhere.pm
rm -f sdk/perl/SQLAnywhere.xs
rm -f sdk/perl/dbdimp.c
rm -f sdk/perl/dbdimp.h
rm -f sdk/perl/dolink.pl
rm -f sdk/perl/eg/blobs.pl
rm -f sdk/perl/eg/connect.pl
rm -f sdk/perl/eg/retrieve.pl
rm -f sdk/perl/lib/DBD/SQLAnywhere/GetInfo.pm
rm -f sdk/perl/license.txt
rm -f sdk/perl/sacapi.h
rm -f sdk/perl/sacapidll.c
rm -f sdk/perl/sacapidll.h
rm -f sdk/perl/sqlerr.h
rm -f sdk/perl/t/base.t
rm -f sdk/perl/t/login.t
rm -f sdk/perl/t/main.t
rm -f sdk/perl/t/place.t
rm -f sdk/perlenv/Makefile.PL
rm -f sdk/perlenv/SAExtEnvIO.pm
rm -f sdk/perlenv/SAPerlGlue.pm
rm -f sdk/perlenv/consts.h
rm -f sdk/perlenv/dolink.pl
rm -f sdk/perlenv/extenv.h
rm -f sdk/perlenv/langload.h
rm -f sdk/perlenv/perlglue.xs
rm -f sdk/php/config.m4
rm -f sdk/php/config.w32
rm -f sdk/php/examples/SAP_logo.gif
rm -f sdk/php/examples/blob.php
rm -f sdk/php/examples/connect.php
rm -f sdk/php/examples/details.php
rm -f sdk/php/examples/error_handling.php
rm -f sdk/php/examples/fetch.php
rm -f sdk/php/examples/fetch_assoc.php
rm -f sdk/php/examples/fetch_object.php
rm -f sdk/php/examples/image-insert.php
rm -f sdk/php/examples/image-retrieve.php
rm -f sdk/php/examples/master.php
rm -f sdk/php/examples/nested.php
rm -f sdk/php/examples/query.php
rm -f sdk/php/examples/resultall.php
rm -f sdk/php/examples/resultalljs.php
rm -f sdk/php/examples/resultallperf.php
rm -f sdk/php/examples/stmt_insert.php
rm -f sdk/php/examples/stored_proc.php
rm -f sdk/php/examples/test.php
rm -f sdk/php/examples/transactions.php
rm -f sdk/php/examples/webisql.php
rm -f sdk/php/examples/webisql_using_extensions.php
rm -f sdk/php/license.txt
rm -f sdk/php/php_sqlany_ver.h
rm -f sdk/php/php_sqlanywhere.h
rm -f sdk/php/sacapi.h
rm -f sdk/php/sacapidll.c
rm -f sdk/php/sacapidll.h
rm -f sdk/php/sqlany_dbg.c
rm -f sdk/php/sqlany_dbg.h
rm -f sdk/php/sqlanywhere.c
rm -f sdk/phpenv/config.m4
rm -f sdk/phpenv/consts.h
rm -f sdk/phpenv/extenv.h
rm -f sdk/phpenv/langload.h
rm -f sdk/phpenv/php_sqlanywhere_extenv.h
rm -f sdk/phpenv/sqlanywhere_extenv.c
rm -f sdk/python/scripts/dbapi20.py
rm -f sdk/python/scripts/runtests.py
rm -f sdk/python/scripts/test.py
rm -f sdk/python/scripts/test_sqlanydb_ext.py
rm -f sdk/python/setup.py
rm -f sdk/python/sqlanydb.py
rm -f sdk/ruby/README
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/CHANGELOG
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/LICENSE
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/README
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/Rakefile
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record/connection_adapters/sqlanywhere_adapter.rb
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/connection.rb
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere.drop.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere2.drop.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere2.sql
rm -f sdk/ruby/dbd-sqlanywhere/CHANGELOG
rm -f sdk/ruby/dbd-sqlanywhere/LICENSE
rm -f sdk/ruby/dbd-sqlanywhere/README
rm -f sdk/ruby/dbd-sqlanywhere/Rakefile
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/SQLAnywhere.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/database.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/driver.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/statement.rb
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/base.rb
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/down.sql
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/up.sql
rm -f sdk/ruby/sqlanywhere/CHANGELOG
rm -f sdk/ruby/sqlanywhere/LICENSE
rm -f sdk/ruby/sqlanywhere/README
rm -f sdk/ruby/sqlanywhere/Rakefile
rm -f sdk/ruby/sqlanywhere/ext/extconf.rb
rm -f sdk/ruby/sqlanywhere/ext/sacapi.h
rm -f sdk/ruby/sqlanywhere/ext/sacapidll.c
rm -f sdk/ruby/sqlanywhere/ext/sacapidll.h
rm -f sdk/ruby/sqlanywhere/ext/sqlanywhere.c
rm -f sdk/ruby/sqlanywhere/lib/README
rm -f sdk/ruby/sqlanywhere/test/sqlanywhere_test.rb
rm -f sdk/ruby/sqlanywhere/test/test.sql
rm -f selinux/README
rm -f selinux/buildfc.sh
rm -f selinux/sqlanywhere.fct
rm -f selinux/sqlanywhere.if
rm -f selinux/sqlanywhere.te
rm -f support/de/ianywhere.html
rm -f support/de/resources.gif
rm -f support/de/updchk.html
rm -f support/en/ianywhere.html
rm -f support/en/resources.gif
rm -f support/en/updchk.html
rm -f support/fr/ianywhere.html
rm -f support/fr/updchk.html
rm -f support/ja/ianywhere.html
rm -f support/ja/resources.gif
rm -f support/ja/updchk.html
rm -f support/zh/ianywhere.html
rm -f support/zh/resources.gif
rm -f support/zh/updchk.html
rm -f thirdpartylegal/SAOnDemand1ThirdPartyLegal.pdf
rm -f thirdpartylegal/SAOnDemand1ThirdPartyLegal.txt
rm -f thirdpartylegal/SQLAnywhere12ThirdPartyLegal.pdf
rm -f thirdpartylegal/SQLAnywhere12ThirdPartyLegal.txt
rm -f tix/default.tix
rm -f ultralite/linux/readme.txt
rm -f ultralite/linux/x86/586/lib/libulbase.a
rm -f ultralite/linux/x86/586/lib/libulrsa.a
rm -f ultralite/linux/x86/586/lib/libulrt.a
rm -f ultralite/linux/x86/586/lib/libulrtc.a
rm -f ultralite/linux/x86/586/uleng12
rm -f ultralite/linux/x86/586/ulstop
rm -f upgrade_*.log
rm -f vcsagent/sadatabase/SADatabase.xml
rm -f vcsagent/sadatabase/SADatabaseTypes.cf
rm -f vcsagent/sadatabase/clean.pl
rm -f vcsagent/sadatabase/monitor.pl
rm -f vcsagent/sadatabase/offline.pl
rm -f vcsagent/sadatabase/online.pl
rm -f vcsagent/saserver/SAServer.xml
rm -f vcsagent/saserver/SAServerTypes.cf
rm -f vcsagent/saserver/clean.pl
rm -f vcsagent/saserver/monitor.pl
rm -f vcsagent/saserver/offline.pl
rm -f vcsagent/saserver/online.pl
rm -rf deployment
rm -rf documentation
rm -rf eclipse
rm -rf openserver
rm -rf sa_help_launcher
rm -rf sun
rm -rf "$HOME/sa_help_launcher" >/dev/null 2>&1
rm -rf "$HOME/.sqlanywhere12" >/dev/null 2>&1
rmdir vcsagent/saserver 2>/dev/null
rmdir vcsagent/sadatabase 2>/dev/null
rmdir vcsagent 2>/dev/null
rmdir ultralite/linux/x86/586/lib 2>/dev/null
rmdir ultralite/linux/x86/586 2>/dev/null
rmdir ultralite/linux/x86 2>/dev/null
rmdir ultralite/linux 2>/dev/null
rmdir ultralite 2>/dev/null
rmdir tix 2>/dev/null
rmdir thirdpartylegal 2>/dev/null
rmdir support/zh 2>/dev/null
rmdir support/ja 2>/dev/null
rmdir support/fr 2>/dev/null
rmdir support/en 2>/dev/null
rmdir support/de 2>/dev/null
rmdir support 2>/dev/null
rmdir selinux 2>/dev/null
rmdir sdk/ruby/sqlanywhere/test 2>/dev/null
rmdir sdk/ruby/sqlanywhere/lib 2>/dev/null
rmdir sdk/ruby/sqlanywhere/ext 2>/dev/null
rmdir sdk/ruby/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test/dbd 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib/dbd 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/test 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record/connection_adapters 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter 2>/dev/null
rmdir sdk/ruby 2>/dev/null
rmdir sdk/python/scripts 2>/dev/null
rmdir sdk/python 2>/dev/null
rmdir sdk/phpenv 2>/dev/null
rmdir sdk/php/examples 2>/dev/null
rmdir sdk/php 2>/dev/null
rmdir sdk/perlenv 2>/dev/null
rmdir sdk/perl/t 2>/dev/null
rmdir sdk/perl/lib/DBD/SQLAnywhere 2>/dev/null
rmdir sdk/perl/lib/DBD 2>/dev/null
rmdir sdk/perl/lib 2>/dev/null
rmdir sdk/perl/eg 2>/dev/null
rmdir sdk/perl 2>/dev/null
rmdir sdk/include 2>/dev/null
rmdir sdk/dbcapi/examples 2>/dev/null
rmdir sdk/dbcapi 2>/dev/null
rmdir sdk/c 2>/dev/null
rmdir sdk 2>/dev/null
rmdir scripts/adata 2>/dev/null
rmdir scripts 2>/dev/null
rmdir samples/ultralite/starter 2>/dev/null
rmdir samples/ultralite/custdb/linux 2>/dev/null
rmdir samples/ultralite/custdb 2>/dev/null
rmdir samples/ultralite 2>/dev/null
rmdir samples/sqlanywhere/sql 2>/dev/null
rmdir samples/sqlanywhere/performancetransaction 2>/dev/null
rmdir samples/sqlanywhere/performancetracetime 2>/dev/null
rmdir samples/sqlanywhere/performanceinsert 2>/dev/null
rmdir samples/sqlanywhere/performancefetch 2>/dev/null
rmdir samples/sqlanywhere/oemstring 2>/dev/null
rmdir samples/sqlanywhere/javainvoice 2>/dev/null
rmdir samples/sqlanywhere/http 2>/dev/null
rmdir samples/sqlanywhere/externalprocedures 2>/dev/null
rmdir samples/sqlanywhere/externallibrariesfulltext 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments/php 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments/perl 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments/externc 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments 2>/dev/null
rmdir samples/sqlanywhere/diskfull 2>/dev/null
rmdir samples/sqlanywhere/dbtools 2>/dev/null
rmdir samples/sqlanywhere/c 2>/dev/null
rmdir samples/sqlanywhere 2>/dev/null
rmdir samples/qanywhere/server 2>/dev/null
rmdir samples/qanywhere 2>/dev/null
rmdir samples/mobilink/partitioning 2>/dev/null
rmdir samples/mobilink/mlreplay 2>/dev/null
rmdir samples/mobilink/java_authentication 2>/dev/null
rmdir samples/mobilink/globalautoincrement 2>/dev/null
rmdir samples/mobilink/custdb 2>/dev/null
rmdir samples/mobilink/contact 2>/dev/null
rmdir samples/mobilink 2>/dev/null
rmdir samples 2>/dev/null
rmdir res 2>/dev/null
rmdir relayserver/apache/quicksetup_apache 2>/dev/null
rmdir relayserver/apache/bin64s 2>/dev/null
rmdir relayserver/apache/bin64 2>/dev/null
rmdir relayserver/apache/bin32s 2>/dev/null
rmdir relayserver/apache/bin32 2>/dev/null
rmdir relayserver/apache 2>/dev/null
rmdir relayserver 2>/dev/null
rmdir mobilink/upgrade/9.0.2 2>/dev/null
rmdir mobilink/upgrade/9.0.1 2>/dev/null
rmdir mobilink/upgrade/9.0.0 2>/dev/null
rmdir mobilink/upgrade/8.0.x 2>/dev/null
rmdir mobilink/upgrade/8.0.1 2>/dev/null
rmdir mobilink/upgrade/8.0.0 2>/dev/null
rmdir mobilink/upgrade/7.0.x 2>/dev/null
rmdir mobilink/upgrade/12.0.0 2>/dev/null
rmdir mobilink/upgrade/11.0.x 2>/dev/null
rmdir mobilink/upgrade/10.0.x 2>/dev/null
rmdir mobilink/upgrade 2>/dev/null
rmdir mobilink/setup 2>/dev/null
rmdir mobilink 2>/dev/null
rmdir lib64 2>/dev/null
rmdir lib32 2>/dev/null
rmdir java 2>/dev/null
rmdir documentation/zh 2>/dev/null
rmdir documentation/ja 2>/dev/null
rmdir documentation/en/pdf 2>/dev/null
rmdir documentation/en 2>/dev/null
rmdir documentation/eclipse/plugins 2>/dev/null
rmdir documentation/eclipse 2>/dev/null
rmdir documentation/de 2>/dev/null
rmdir documentation 2>/dev/null
rmdir deployment/res/scripts 2>/dev/null
rmdir deployment/res/language/zh 2>/dev/null
rmdir deployment/res/language/ja 2>/dev/null
rmdir deployment/res/language/fr 2>/dev/null
rmdir deployment/res/language/en 2>/dev/null
rmdir deployment/res/language/de 2>/dev/null
rmdir deployment/res/language 2>/dev/null
rmdir deployment/res 2>/dev/null
rmdir deployment/lib64 2>/dev/null
rmdir deployment/lib32 2>/dev/null
rmdir deployment/bin64s 2>/dev/null
rmdir deployment/bin64 2>/dev/null
rmdir deployment/bin32s 2>/dev/null
rmdir deployment/bin32 2>/dev/null
rmdir deployment 2>/dev/null
rmdir charsets/unicode 2>/dev/null
rmdir charsets 2>/dev/null
rmdir bin64s/language/zh 2>/dev/null
rmdir bin64s/language/ja 2>/dev/null
rmdir bin64s/language/fr 2>/dev/null
rmdir bin64s/language/en 2>/dev/null
rmdir bin64s/language/de 2>/dev/null
rmdir bin64s/language 2>/dev/null
rmdir bin64s/dbsvc_scripts 2>/dev/null
rmdir bin64s 2>/dev/null
rmdir bin64/language/zh 2>/dev/null
rmdir bin64/language/ja 2>/dev/null
rmdir bin64/language/fr 2>/dev/null
rmdir bin64/language/en 2>/dev/null
rmdir bin64/language/de 2>/dev/null
rmdir bin64/language 2>/dev/null
rmdir bin64/dbsvc_scripts 2>/dev/null
rmdir bin64 2>/dev/null
rmdir bin32s/language/zh 2>/dev/null
rmdir bin32s/language/ja 2>/dev/null
rmdir bin32s/language/fr 2>/dev/null
rmdir bin32s/language/en 2>/dev/null
rmdir bin32s/language/de 2>/dev/null
rmdir bin32s/language 2>/dev/null
rmdir bin32s/dbsvc_scripts 2>/dev/null
rmdir bin32s 2>/dev/null
rmdir bin32/language/zh 2>/dev/null
rmdir bin32/language/ja 2>/dev/null
rmdir bin32/language/fr 2>/dev/null
rmdir bin32/language/en 2>/dev/null
rmdir bin32/language/de 2>/dev/null
rmdir bin32/language 2>/dev/null
rmdir bin32/dbsvc_scripts 2>/dev/null
rmdir bin32 2>/dev/null
LO=`find "$SAROOT" -type f 2>/dev/null | grep -v uninstall.sh`
[ "$LO" = "" ] && rm -f uninstall.sh
rm -f /usr/share/applications/ianywhere-12* 2>/dev/null 
rm -f /usr/share/desktop-directories/ianywhere-12* 2>/dev/null 
rm -f /etc/xdg/menus/applications-merged/ianywhere-12* 2>/dev/null 
rm -f "$HOME"/.local/share/applications/ianywhere-12* 2>/dev/null 
rm -f "$HOME"/.local/share/desktop-directories/ianywhere-12* 2>/dev/null 
rm -f "$HOME"/.config/menus/applications-merged/ianywhere-12* 2>/dev/null 
cd 
rmdir "$SAROOT" 2>/dev/null
[ -r "$OPWD" ] && cd "$OPWD"
